/* Project U — lang.js — Traducciones 7 idiomas */
/* Reconstrucción completa - Prioridad EN → FR → KO → ZH → RU → PT → ES */

const T_raw = {
  // ==================== ESPAÑOL (ES) ====================
  es: {
    // Hero
    'hero.sub': 'Para Principiantes — Sin Ofender',
    'frase1': 'No soy dueño de la Verdad — pero <span>Conocimiento + Organización = Poder.</span>',
    'frase2': 'No le temas al RNG. No es tu amigo, ni tu enemigo... <span>solo te tira sugerencias.</span>',
    
    // Tracker
    'tracker.title': '// tracker · ¿dónde estás ahora?',
    'lbl.act': 'Act actual',
    'lbl.build': 'Tipo de build',
    'lbl.rng': 'Tu situación con el RNG',
    'lbl.sit': 'Problema actual',
    'btn.analyze': '⟶ Analizar situación',
    'sel': '— Seleccioná —',
    'epilogo': 'Epílogo',
    
    // Build types
    'b.fisico': 'Físico (Guerrero)',
    'b.veneno': 'Veneno (Poison)',
    'b.elemental': 'Daño Elemental',
    'b.crit': 'Crítico',
    'b.inv': 'Invocador',
    'b.noidea': 'No sé todavía',
    
    // RNG situations
    'r.bien': 'Me está yendo bien',
    'r.mal': 'Me cae lo que no necesito',
    'r.conf': 'No sé qué hacer con lo que tengo',
    
    // Situations
    'sit.none': '— Sin problema —',
    'sit.dmg': 'Bajo daño',
    'sit.glass': 'Muero rápido',
    'sit.stuck': 'Progreso lento',
    'sit.lucky': 'Muchos drops buenos',
    
    // Philosophy
    'philo.title': '// filosofía · el manual de adaptabilidad',
    'p1.h': 'Conocimiento es poder',
    'p1.p': 'Entender cómo funciona el sistema de runas, las resistencias y el scaling de daño te da <em>ventaja real</em>. No necesitás un build copiado si entendés los fundamentos.',
    'p2.h': 'El RNG es neutral',
    'p2.p': 'No te persigue ni te favorece. Te da opciones y <em>vos decidís qué hacer con ellas</em>. El jugador adaptable siempre tiene más caminos que el que fuerza.',
    'p3.h': 'El Baúl es tu aliado',
    'p3.p': 'Lo que hoy no te sirve, <em>es el poder del mañana</em>. Guardá todo. Otro personaje, otro momento, otra build — todo tiene su momento.',
    'p4.h': 'Adaptate, no fuerces',
    'p4.p': 'Si el loot te empuja hacia otra dirección, <em>escuchalo</em>. Pivotar no es rendirse — es inteligencia táctica. El RNG muchas veces muestra un camino mejor.',
    
    // Knowledge Learned
    'kl.title': '// knowledge.learned — lo que nadie te cuenta',
    'k1.h': 'El juego no está vacío',
    'k1.p': '<em>"No tengas miedo si no ves muchos jugadores. El juego puede sentirse vacío al principio — pero su verdadera naturaleza vive en el endgame. Ahí es donde está todo el mundo."</em>',
    'k2.h': 'Tu primer personaje es tu maestro',
    'k2.p': 'No es tu main — es tu escuela. Cada error, cada pivot de build, cada ítem guardado en el baúl es una lección. <em>La satisfacción de llegar al endgame es real.</em>',
    'k3.h': 'Las transiciones son el juego',
    'k3.p': 'Whirlwind → Toxic Flame → Icy Arrow. Cada build fue una respuesta a lo que el juego ofrecía. <em>Adaptarse no es rendirse — es jugar bien.</em>',
    'k4.h': 'El drop malo no existe',
    'k4.p': 'Lo que hoy no usás, <em>es el poder de otro personaje mañana.</em> El baúl no es desorden — es planificación a largo plazo.',
    'k5.h': 'El completionista es recompensado',
    'k5.p': 'Explorar cada rincón, completar cada mapa al 100% y cumplir misiones secundarias <em>no es tiempo perdido</em> — el juego lo premia con logros, recursos y contenido exclusivo del Epílogo.',
    'k6.h': 'Hasta las cajas importan',
    'k6.p': 'Romper barriles, cajas y objetos del escenario parece insignificante — pero <em>cuenta para logros reales.</em> En Undecember cada acción tiene peso. Nunca ignorés el entorno.',
    'k7.h': 'No necesitás un alt enseguida',
    'k7.p': 'El juego <em>se adapta solo al progreso</em>. Las Jewells aparecen en el Act 6, las cartas del Caos recién al final del Act 13. No hay necesidad de crear una mula desde el inicio — aprendé primero qué guardar, qué vender y qué romper.',
    'k8.h': '¿Es P2W? La respuesta honesta',
    'k8.p': 'En mi experiencia: <em>no</em>. Pero la organización sí importa. Saber gestionar el espacio del banco, decidir qué pasarle a otros personajes y qué descartar <em>vale más que cualquier item comprado</em>.',
    'k9.h': 'Las resistencias se diluyen al avanzar',
    'k9.p': 'El 75% que tenías en el Act 3 <em>puede no alcanzar en el Act 7</em>. A medida que avanzás de episodio, los enemigos escalan y las resistencias se "caen" relativamente. Revisalas cada vez que cambiás de episodio — no son "set and forget".',
    'k10.h': 'Algunos items son Game Changers',
    'k10.p': 'No todos los items son una mejora incremental. Algunos cambian el rumbo completo — <em>un antes y un después</em>. No siempre los reconocés al equiparlos, pero lo notás cuando el juego empieza a fluir diferente. Guardá todo hasta estar seguro.',
    'k11.h': 'Los bosses como test de build',
    'k11.p': 'Hay bosses que actúan como un checkpoint natural — sin spoilear cuáles. Si no podés con uno, el juego no te está castigando: <em>te está mostrando algo sobre tu build</em>. No es necesariamente que estés mal, sino que hay algo por ajustar antes de seguir.',
    'k12.h': 'Cambio forzado vs. Ganancias',
    'k12.p': 'A veces el juego te obliga a perder algo — puntos del Zodiaco, stats, runas o equipo — para desbloquear un progreso mayor. <em>No es un castigo, es el sistema adaptándose.</em> Aceptar ese cambio forzado es lo que separa al jugador que avanza del que se queda trabado.',
    
    // Path / Timeline
    'path.title': '// MI CAMINO: EVOLUCIÓN POST-64',
    'path.p1': 'Buscaba críticos amarillos entre los blancos. Muy satisfactorio, pero las resistencias me frenaron en el Act 6. <span style="color:var(--cyan)">Primera lección: el juego te avisa cuando un build llegó a su techo.</span>',
    'path.p2': 'Transición al daño fijo (<span style="color:var(--red2)">Max-Min DMG</span>). Estabilidad pura para superar el pico de dificultad. Cada cambio de build significó guardar items distintos — el baúl empezó a crecer con propósito.',
    'path.p3': 'La meta: <span style="color:var(--gold2);font-weight:bold;font-size:1.1rem;text-shadow:0 0 8px rgba(201,168,76,0.5)">AMARILLOS ENORMES</span>. Velocidad y críticos masivos. Recompensa a la organización.',
    'path.zodiac.title': '// ZODIAC RESET · VENTANA GRATUITA',
    'path.zodiac.p': 'El juego permite resetear el Zodiaco <span style="color:var(--cyan)">Gratis hasta antes de matar el jefe final del Act 10</span>. Esto no es solo una ventaja — es una invitación a probar builds diferentes sin miedo. Cada prueba genera drops distintos, cada drop va al baúl, y el baúl crece. <span style="color:var(--gold)">Experimentar antes del Act 10 no es tiempo perdido — es inversión en el inventario.</span>',
    
    // Early Game
    'early.title': '📖 Early Game: cada acción cuenta',
    'early.intro': '"No es un juego difícil, pero hay mucho por hacer. Cada acción pequeña construye un personaje enorme."',
    'early.comp.h': 'El Compendio trabaja para vos',
    'early.comp.p': 'Una vez desbloqueado (Act 1 o 2), prestá atención a las runas que elegís. <em>Evitá repetirlas al principio</em> — concentrate en conseguir runas nuevas para sumar puntos y obtener mejoras permanentes. ¡Cada punto suma! Lo mismo aplica para los items Únicos: guardalos para el buff pasivo.',
    'early.alch.h': 'La mesa de alquimia nunca descansa',
    'early.alch.p': 'Empezá a craftear temprano. No dejes la mesa de alquimia quieta — subir el nivel de Maestría es la <em>única forma</em> de desbloquear Pociones Únicas y crafteo avanzado más adelante. La eficiencia es la clave.',
    'early.mys.h': 'Gastá el oro en Misteriosos',
    'early.mys.p': 'Entre el Mid y Late Game, mientras el crafteo avanzado todavía no es del todo viable, gastar el oro ahorrado en <em>Objetos Misteriosos</em> es una gran opción. Es la mejor forma de buscar bases de alto nivel o equipo decente.',
    'early.ach.h': 'Todo cuenta como logro',
    'early.ach.p': 'Agregar amigos, unirse a una guild, completar tareas diarias — <em>cada acción suma puntos de progreso invisible</em>. Los buffs diarios y recompensas de guild son victorias pasivas que muchos ignoran.',
    'early.season.h': 'Temporada > Estándar (mi opinión)',
    'early.season.p': 'Si venís de juegos como PoE, ya sabés cómo funciona: el personaje de Temporada termina en Estándar al final del ciclo. Pero mientras dura, tiene <em>mayor drop de oro, más esencias de alquimia y mejores chances de Únicos</em>. Mi recomendación personal: arrancá en Temporada.',
    'early.hard.h': 'Hardcore vs Normal — no es lo mismo',
    'early.hard.p': 'En Hardcore, si tu personaje muere <em>demasiadas veces sin ser cuidadoso</em>, las consecuencias son permanentes. Normal te da margen para aprender sin ese peso. Para un jugador nuevo: <em>empezá en Normal</em>, aprendé el juego, y cuando te sientas seguro considerá el desafío Hardcore.',
    
    // Acts
    'act.1': 'Act 1', 'act.2': 'Act 2', 'act.3': 'Act 3', 'act.4': 'Act 4', 'act.5': 'Act 5',
    'act.6': 'Act 6', 'act.7': 'Act 7', 'act.8': 'Act 8', 'act.9': 'Act 9', 'act.10': 'Act 10',
    'act.11': 'Act 11', 'act.12': 'Act 12', 'act.13': 'Act 13',
    
    // Optgroups
    'og1': 'Episodio 1 — Tutorial (Act 1–5)',
    'og2': 'Episodio 2 — El juego empieza (Act 6–10)',
    'og3': 'Episodio 3 — Endgame (Act 11–13)',
    'og4': 'Epílogo — Todo desbloqueado',
    
    // About & Footer
    'about.title': 'Acerca de',
    'about.text': 'Esta web-app contiene parte de mis pensamientos, avanzando hacia una visión global. No estoy diciendo cómo jugar; en cambio, cuento mi historia o mi camino a través del juego.',
    'footer.fan': 'Hecho por un fan',
    'endgame.secret': 'El endgame tiene sus propios secretos — esos los descubrís vos.',
    
    // Toolbar
    'toolbar.save': '💾 Guardar build',
    'toolbar.load': '📂 Cargar',
    'toolbar.del': '🗑️ Eliminar',
    'toolbar.export': '📋 Exportar',
    'toolbar.reset': '⟳ Resetear',
    'toolbar.load.ph': '— Cargar build —',
    'toolbar.del.ph': '— Eliminar build —',
    
    // FAQ
    'faq.title': '// faq · preguntas frecuentes',
    'faq.q1': '¿Por qué mis bufos cambian según mis stats base?',
    'faq.a1': 'Project U no es una base de datos estática. Usa <strong>Condicionales de Atributo Comparado</strong>. Si tu Energía supera a tu Fuerza, tu Barrera escala un 10% extra. Las stats no existen en el vacío — el portal refleja la realidad del juego.',
    'faq.q2': '¿Por qué no veo ítems comunes o raros?',
    'faq.a2': 'Project U está diseñado para el <strong>Theorycrafting de alto nivel</strong>. Los ítems <em>Únicos</em> son los que definen una build. Los ítems genéricos se agregarán en futuras actualizaciones.',
    'faq.q3': '¿El bufo del Baúl se suma al del ítem equipado?',
    'faq.a3': 'Sí. El sistema detecta si el ítem está <strong>Guardado en el Baúl (✦)</strong> y activa el beneficio pasivo de colección, independientemente de lo equipado en el slot activo.',
    'faq.q4': '¿Puedo guardar más de un ejemplar del mismo ítem Único?',
    'faq.a4': 'No. Project U sigue la regla de <strong>Ejemplar Único</strong>. Una vez que un ítem está en Gris, su beneficio queda permanente en tu Wardrobe.',
    'faq.q5': '¿Por qué el Escudo no está en la pestaña de Armaduras?',
    'faq.a5': 'El <strong>Escudo es una pieza de mano secundaria</strong>. Esto permite validar si tu build es compatible con armas de dos manos.',
    'faq.q6': '¿Cómo me ayuda Project U a decidir entre dos ítems únicos?',
    'faq.a6': 'El sistema de <strong>Condicionales de Atributo Comparado</strong> te advertirá si un cambio de equipo rompe una sinergia de stats. La decisión final es tuya.',
    'faq.q7': '¿Por qué usamos Seal of Chaos Resist en lugar de Cold Armor?',
    'faq.a7': 'Aunque somos una build de Agilidad (Verde), el Seal of Chaos Resist (Azul) es innegociable. <strong>La armadura física no sirve contra el daño de Caos.</strong> Sacrificamos defensa física plana por supervivencia pura — es el daño que suele one-shotear a los arqueros en mapas altos.',
    'faq.q8': '¿Cómo se logra la Metralleta de Movilidad?',
    'faq.a8': 'El secreto es <strong>Roll + Use Count</strong>. Al equipar Use Count, el contador de cargas sube a 3. Podés reposicionarte tres veces seguidas antes del cooldown global. En peleas de jefes con áreas grandes, esto es lo que te mantiene vivo.',
    'faq.q9': '¿Cuál es la importancia del estado de Overheat?',
    'faq.a9': 'La Icy Arrow genera Overheat, y lo aprovechamos con <strong>Heat Cycle</strong>. Al llegar a High Temperature (&gt;40%), recibimos <em>+126.9% de Critical Rate</em>. Mantenemos el ritmo para estar siempre en el pico de críticos.',
    'faq.q10': '¿Por qué invertir tanto en la Frost Sentry?',
    'faq.a10': 'La torreta no es solo daño extra — es escalado, control y distracción. Con <strong>Life Imbued</strong>: +1% DMG por cada 2500 HP de la torreta. Con <strong>Precise Sentry</strong>: críticos constantes y congelación. <em>A ninguna runa la veo como secundaria.</em>',
    
    // Runas
    'runes.red.label': 'Rojo — Fuerza',
    'runes.green.label': 'Verde — Agilidad',
    'runes.blue.label': 'Azul — Inteligencia',
    'runes.white.label': 'Blanco — Universal',
    'runes.red.name': 'Rojo',
    'runes.green.name': 'Verde',
    'runes.blue.name': 'Azul',
    'runes.white.name': 'Blanco',
    'runes.red.attr': 'Fuerza (STR)',
    'runes.green.attr': 'Agilidad (AGI)',
    'runes.blue.attr': 'Inteligencia (INT)',
    'runes.white.attr': 'Universal',
    'runes.red.focus': 'Supervivencia · Físico',
    'runes.green.focus': 'Velocidad · Destreza',
    'runes.blue.focus': 'Magia · Utilidad',
    'runes.white.focus': 'Enlace Libre (cualquier color)',
    'runes.table.color': 'Color',
    'runes.table.attr': 'Atributo',
    'runes.table.focus': 'Enfoque de Combate',
    'runes.skill.title': '// skill runes · build actual',
    'runes.link.title': '// link runes · modificadores equipados',
    'runes.ref.text': '¿Dudas? Consultá la librería completa →',
    'no.conditionals': 'Sin condicionales',
    
    // Gear Matrix Filters
    'filter.weapons': '⚔ Armas',
    'filter.armor': '🛡 Armaduras',
    'filter.acc': '💍 Accesorios',
    'filter.runes': '🔗 Link Runes',
    
    // Stats
    'stats.str': 'STR',
    'stats.dex': 'DEX',
    'stats.int': 'INT',
    'stats.hpfull': 'HP Full',
    
    // Wardrobe
    'wardrobe.active': '// bufos de armario activos',
    'wardrobe.stored': '✦ Guardado en el Baúl (bufo activo)',
    'wardrobe.store': '○ Guardar en el Baúl',
    'wardrobe.empty': 'Sin ítems guardados.',
    'unique.badge': 'Único',
    
    // Weapon Matrix
    'weapon.main.type': 'Mano Principal · Tipo',
    'weapon.main.name': 'Mano Principal · Nombre',
    'weapon.off.type': 'Mano Secundaria · Tipo',
    'weapon.off.name': 'Mano Secundaria · Nombre',
    'weapon.type.placeholder': '— Tipo de arma —',
    'weapon.name.placeholder': '— Seleccioná tipo primero —',
    'weapon.off.none': 'Sin mano secundaria',
    'btn.validate': '⟶ Validar Combinacion',
    'shield.label': '🛡️ Escudo',
    'shield.none': '— Ninguno —',
    'shield.light': 'Escudo Ligero',
    'shield.heavy': 'Escudo Pesado',
    'shield.tower': 'Escudo de Torres',
    'shield.warning': '⚠ No compatible con armas de dos manos',
    
    // Build Saver
    'build.save.prompt': 'Nombre para esta build:',
    'build.save.success': '✓ Build guardada',
    'build.load.success': '✓ Build cargada',
    'build.delete.confirm': '¿Eliminar build?',
    'build.delete.success': '✓ Build eliminada',
    'build.export.copied': '📋 Build copiada al portapapeles!',
    'build.reset.confirm': '⚠️ ¿Resetear TODOS los selects y stats?',
    'build.reset.success': '✓ Todo reseteado',
    'build.load.prompt': 'Seleccioná una build para cargar.',
    'build.delete.prompt': 'Seleccioná una build para eliminar.',

    // Gear Slots
    'gear.slot.casco': 'Casco',
    'gear.slot.pechera': 'Pechera',
    'gear.slot.hombreras': 'Hombreras',
    'gear.slot.guantes': 'Guantes',
    'gear.slot.botas': 'Botas',
    'gear.slot.necklace': 'Necklace',
    'gear.slot.cinturon': 'Cinturón',
    'gear.slot.anillo': 'Anillo',
  },

  // ==================== INGLÉS (EN) ====================
  en: {
    'hero.sub': 'For Dummies — Without the Insult',
    'frase1': 'I don\'t own the Truth — but <span>Knowledge + Organization = Power.</span>',
    'frase2': 'Don\'t fear the RNG. It\'s not your friend, nor your enemy... <span>it only throws suggestions.</span>',
    'tracker.title': '// tracker · where are you now?',
    'lbl.act': 'Current Act',
    'lbl.build': 'Build type',
    'lbl.rng': 'Your RNG situation',
    'lbl.sit': 'Current issue',
    'btn.analyze': '⟶ Analyze my situation',
    'sel': '— Select —',
    'epilogo': 'Epilogue',
    'b.fisico': 'Physical (Warrior)',
    'b.veneno': 'Poison',
    'b.elemental': 'Elemental Damage',
    'b.crit': 'Critical',
    'b.inv': 'Summoner',
    'b.noidea': 'Not sure yet',
    'r.bien': 'Going well',
    'r.mal': 'Getting what I don\'t need',
    'r.conf': 'Not sure what to do with what I have',
    'sit.none': '— No issue —',
    'sit.dmg': 'Low damage',
    'sit.glass': 'Dying too fast',
    'sit.stuck': 'Slow progress',
    'sit.lucky': 'Getting great drops',
    'philo.title': '// philosophy · the adaptability manual',
    'p1.h': 'Knowledge is power',
    'p1.p': 'Understanding how the rune system, resistances and damage scaling work gives you a <em>real edge</em>. You don\'t need a copied build if you understand the fundamentals.',
    'p2.h': 'RNG is neutral',
    'p2.p': 'It doesn\'t chase you or favor you. It gives you options and <em>you decide what to do with them</em>. The adaptable player always has more paths than the one who forces.',
    'p3.h': 'The Chest is your ally',
    'p3.p': 'What doesn\'t serve you today <em>is tomorrow\'s power</em>. Keep everything. Another character, another moment, another build — everything has its time.',
    'p4.h': 'Adapt, don\'t force',
    'p4.p': 'If the loot pushes you in another direction, <em>listen to it</em>. Pivoting is not giving up — it\'s tactical intelligence. The RNG often shows you a better path.',
    'kl.title': '// knowledge.learned — what nobody tells you',
    'k1.h': 'The game is not empty',
    'k1.p': '<em>"Don\'t be afraid if you don\'t see many players around. The game may feel empty at first — but its true nature lives in the endgame. That\'s where everyone is."</em>',
    'k2.h': 'Your first character is your teacher',
    'k2.p': 'It\'s not your main — it\'s your school. Every mistake, every build pivot, every item saved in the chest is a lesson. <em>The satisfaction of reaching endgame is real.</em>',
    'k3.h': 'Transitions are the game',
    'k3.p': 'Whirlwind → Toxic Flame → Icy Arrow. Each build was a response to what the game offered. <em>Adapting is not giving up — it\'s playing well.</em>',
    'k4.h': 'There\'s no such thing as a bad drop',
    'k4.p': 'What you don\'t use today <em>is another character\'s power tomorrow.</em> The chest isn\'t clutter — it\'s long-term planning.',
    'k5.h': 'Completionists are rewarded',
    'k5.p': 'Exploring every corner, completing every map at 100% and doing side quests <em>is not wasted time</em> — the game rewards it with achievements, resources and exclusive Epilogue content.',
    'k6.h': 'Even boxes matter',
    'k6.p': 'Breaking barrels, boxes and objects in the environment seems insignificant — but <em>it counts for real achievements.</em> In Undecember every action has weight. Never ignore your surroundings.',
    'k7.h': 'You don\'t need an alt right away',
    'k7.p': 'The game <em>adapts itself to your progress</em>. Jewells appear in Act 6, Chaos cards only at the end of Act 13. There\'s no need to create a mule from the start — first learn what to keep, what to sell and what to break.',
    'k8.h': 'Is it P2W? The honest answer',
    'k8.p': 'In my experience: <em>no</em>. But organization does matter. Knowing how to manage your bank space, deciding what to pass to other characters and what to discard <em>is worth more than any purchased item</em>.',
    'k9.h': 'Resistances drop as you progress',
    'k9.p': 'The 75% you had in Act 3 <em>may not hold in Act 7</em>. As you advance through episodes, enemies scale and resistances relatively fall off. Check them every time you change episode — they are not set and forget.',
    'k10.h': 'Some items are Game Changers',
    'k10.p': 'Not every item is an incremental upgrade. Some change the whole direction — <em>a before and after</em>. You don\'t always recognize them when you equip them, but you notice when the game starts flowing differently. Keep everything until you\'re sure.',
    'k11.h': 'Bosses as a build test',
    'k11.p': 'Some bosses act as a natural checkpoint — without spoiling which ones. If you can\'t get past one, the game isn\'t punishing you: <em>it\'s showing you something about your build</em>. It doesn\'t necessarily mean you\'re wrong — just that something needs adjusting before moving on.',
    'k12.h': 'Forced Change vs. Gains',
    'k12.p': 'Sometimes the game forces you to lose something — Zodiac points, stats, runes or gear — to unlock greater progress. <em>It\'s not a punishment, it\'s the system adapting.</em> Accepting that forced change is what separates the player who advances from the one who stays stuck.',
    'path.title': '// MY PATH: POST-64 EVOLUTION',
    'path.p1': 'Chasing yellow crits among whites. Visually satisfying, but resistances stopped me in Act 6. <span style="color:var(--cyan)">First lesson: the game tells you when a build has hit its ceiling.</span>',
    'path.p2': 'Transition to fixed damage (<span style="color:var(--red2)">Max-Min DMG</span>). Pure stability to overcome the difficulty spike. Each build change meant saving different items — the chest started growing with purpose.',
    'path.p3': 'The goal: <span style="color:var(--gold2);font-weight:bold;font-size:1.1rem;text-shadow:0 0 8px rgba(201,168,76,0.5)">MASSIVE YELLOWS</span>. Speed and massive crits. Reward for organization.',
    'path.zodiac.title': '// ZODIAC RESET · FREE WINDOW',
    'path.zodiac.p': 'The game allows free Zodiac resets <span style="color:var(--cyan)">free until Act 10 final boss</span>. This isn\'t just an advantage — it\'s an invitation to try different builds without fear. Each attempt generates different drops, each drop goes to the chest, and the chest grows. <span style="color:var(--gold)">Experimenting before Act 10 is not wasted time — it\'s an investment in your inventory.</span>',
    'early.title': '📖 Early Game: every action counts',
    'early.intro': '"This is not a hard game, but there is a lot of stuff to do. Every small action builds a massive character."',
    'early.comp.h': 'The Compendium works for you',
    'early.comp.p': 'Once unlocked (Act 1 or 2), keep a close eye on the runes you pick. <em>Avoid duplicates early on</em> — focus on collecting new ones to gain points and permanent stat boosts. Every point counts! The same goes for Unique items: save them for the passive buff.',
    'early.alch.h': 'The alchemy table never rests',
    'early.alch.p': 'Start crafting early. Don\'t let your alchemy table sit idle — leveling up your Mastery is the <em>only way</em> to unlock Unique Potions and advanced crafting later on. Efficiency is key.',
    'early.mys.h': 'Spend gold on Mysterious Items',
    'early.mys.p': 'Between Mid and Late Game, since advanced crafting might not be fully viable yet, spending your saved Gold on <em>Mysterious Items</em> is a smart move. It\'s the best way to fish for high-tier bases or decent gear.',
    'early.ach.h': 'Everything counts as achievement',
    'early.ach.p': 'Adding friends, joining a guild, completing daily tasks — <em>every action adds invisible progress points</em>. Daily buffs and guild rewards are passive wins that most players ignore.',
    'early.season.h': 'Season > Standard (personal take)',
    'early.season.p': 'If you come from games like PoE, you already know how it works: the Season character moves to Standard at the end of the cycle. But while it lasts, it has <em>higher gold drops, more alchemy essences and better Unique chances</em>. My personal take: start in Season.',
    'early.hard.h': 'Hardcore vs Normal — not the same thing',
    'early.hard.p': 'In Hardcore, if your character dies <em>too many times without being cautious</em>, the consequences are permanent. Normal gives you room to learn without that pressure. For a new player: <em>start in Normal</em>, learn the game, and once you feel confident consider the Hardcore challenge.',
    'act.1': 'Act 1', 'act.2': 'Act 2', 'act.3': 'Act 3', 'act.4': 'Act 4', 'act.5': 'Act 5',
    'act.6': 'Act 6', 'act.7': 'Act 7', 'act.8': 'Act 8', 'act.9': 'Act 9', 'act.10': 'Act 10',
    'act.11': 'Act 11', 'act.12': 'Act 12', 'act.13': 'Act 13',
    'og1': 'Episode 1 — Tutorial (Acts 1–5)',
    'og2': 'Episode 2 — The game begins (Acts 6–10)',
    'og3': 'Episode 3 — Endgame (Acts 11–13)',
    'og4': 'Epilogue — Everything unlocked',
    'about.title': 'About',
    'about.text': 'This web-app has part of my thoughts, moving into a global vision. I\'m not telling how to play; instead of it, I\'m telling my story or my way through the game.',
    'footer.fan': 'Made by a fan',
    'endgame.secret': 'The endgame has its own secrets — those are yours to discover.',
    'toolbar.save': '💾 Save build',
    'toolbar.load': '📂 Load',
    'toolbar.del': '🗑️ Delete',
    'toolbar.export': '📋 Export',
    'toolbar.reset': '⟳ Reset all',
    'toolbar.load.ph': '— Load build —',
    'toolbar.del.ph': '— Delete build —',
    'faq.title': '// faq · frequently asked questions',
    'faq.q1': 'Why do my buffs change based on my base stats?',
    'faq.a1': 'Project U is not a static database. It uses <strong>Compared Attribute Conditionals</strong>. If your Energy exceeds your Strength, your Barrier scales an extra 10%. Stats don\'t exist in a vacuum.',
    'faq.q2': 'Why don\'t I see common or rare items?',
    'faq.a2': 'Project U is designed for high-level <strong>Theorycrafting</strong>. <em>Unique</em> items define a build. Generic items will be added in future Compendium updates.',
    'faq.q3': 'Does the Chest buff stack with the equipped item buff?',
    'faq.a3': 'Yes. The system detects if the item is <strong>Stored in the Chest (✦)</strong> and activates the passive collection benefit, regardless of what\'s equipped in the active slot.',
    'faq.q4': 'Can I store more than one copy of the same Unique item?',
    'faq.a4': 'No. Project U follows the <strong>Unique Copy</strong> rule. Once an item is Grey, its collection benefit is permanently active in your Wardrobe.',
    'faq.q5': 'Why isn\'t the Shield in the Armor tab?',
    'faq.a5': 'The <strong>Shield is an off-hand piece</strong>. This allows correct validation of whether your build is compatible with two-handed weapons.',
    'faq.q6': 'How does Project U help me decide between two unique items?',
    'faq.a6': 'The <strong>Compared Attribute Conditionals</strong> system will warn you if an equipment change breaks a stat synergy. The final decision is yours.',
    'faq.q7': 'Why do we use Seal of Chaos Resist instead of Cold Armor?',
    'faq.a7': 'Even though this is an Agility (Green) build, the Seal of Chaos Resist (Blue) is non-negotiable. <strong>Physical armor does nothing against Chaos damage.</strong> We trade flat physical defense for pure survivability — Chaos damage is what one-shots archers in high-level maps.',
    'faq.q8': 'How does the Mobility Machine Gun work?',
    'faq.a8': 'The secret is <strong>Roll + Use Count</strong>. Equipping Use Count raises the charge counter to 3. You can reposition three times in a row before the global cooldown. In boss fights with large AoE zones, this is what keeps you alive.',
    'faq.q9': 'Why is the Overheat state important?',
    'faq.a9': 'Icy Arrow generates Overheat, and we exploit it with <strong>Heat Cycle</strong>. When we reach High Temperature (&gt;40%), we receive <em>+126.9% Critical Rate</em>. We maintain rhythm to always stay at the critical peak.',
    'faq.q10': 'Why invest so much in Frost Sentry?',
    'faq.a10': 'The turret is not just extra damage — it is scaling, control and distraction. With <strong>Life Imbued</strong>: +1% DMG per 2500 sentry HP. With <strong>Precise Sentry</strong>: constant crits and freezing. <em>I see no rune as secondary — all fill a role.</em>',
    'runes.red.label': 'Red — Strength',
    'runes.green.label': 'Green — Agility',
    'runes.blue.label': 'Blue — Intelligence',
    'runes.white.label': 'White — Universal',
    'runes.red.name': 'Red',
    'runes.green.name': 'Green',
    'runes.blue.name': 'Blue',
    'runes.white.name': 'White',
    'runes.red.attr': 'Strength (STR)',
    'runes.green.attr': 'Agility (AGI)',
    'runes.blue.attr': 'Intelligence (INT)',
    'runes.white.attr': 'Universal',
    'runes.red.focus': 'Survival · Physical',
    'runes.green.focus': 'Speed · Dexterity',
    'runes.blue.focus': 'Magic · Utility',
    'runes.white.focus': 'Free Link (any color)',
    'runes.table.color': 'Color',
    'runes.table.attr': 'Attribute',
    'runes.table.focus': 'Combat Focus',
    'runes.skill.title': '// skill runes · current build',
    'runes.link.title': '// link runes · equipped modifiers',
    'runes.ref.text': 'In case of doubts, check the full Runes Library →',
    'no.conditionals': 'No conditionals',
    'filter.weapons': '⚔ Weapons',
    'filter.armor': '🛡 Armor',
    'filter.acc': '💍 Accessories',
    'filter.runes': '🔗 Link Runes',
    'stats.str': 'STR',
    'stats.dex': 'DEX',
    'stats.int': 'INT',
    'stats.hpfull': 'HP Full',
    'wardrobe.active': '// active wardrobe buffs',
    'wardrobe.stored': '✦ Stored in Chest (buff active)',
    'wardrobe.store': '○ Store in Chest',
    'wardrobe.empty': 'No stored items.',
    'unique.badge': 'Unique',
    'weapon.main.type': 'Main Hand · Type',
    'weapon.main.name': 'Main Hand · Name',
    'weapon.off.type': 'Off Hand · Type',
    'weapon.off.name': 'Off Hand · Name',
    'weapon.type.placeholder': '— Weapon type —',
    'weapon.name.placeholder': '— Select type first —',
    'weapon.off.none': 'No off-hand',
    'btn.validate': '⟶ Validate Combination',
    'shield.label': '🛡️ Shield',
    'shield.none': '— None —',
    'shield.light': 'Light Shield',
    'shield.heavy': 'Heavy Shield',
    'shield.tower': 'Tower Shield',
    'shield.warning': '⚠ Not compatible with two-handed weapons',
    'build.save.prompt': 'Name for this build:',
    'build.save.success': '✓ Build saved',
    'build.load.success': '✓ Build loaded',
    'build.delete.confirm': 'Delete build?',
    'build.delete.success': '✓ Build deleted',
    'build.export.copied': '📋 Build copied to clipboard!',
    'build.reset.confirm': '⚠️ Reset ALL selects and stats?',
    'build.reset.success': '✓ Everything reset',
    'build.load.prompt': 'Select a build to load.',
    'build.delete.prompt': 'Select a build to delete.',

    // Gear Slots
    'gear.slot.casco': 'Helmet',
    'gear.slot.pechera': 'Chestplate',
    'gear.slot.hombreras': 'Pauldrons',
    'gear.slot.guantes': 'Gloves',
    'gear.slot.botas': 'Boots',
    'gear.slot.necklace': 'Necklace',
    'gear.slot.cinturon': 'Belt',
    'gear.slot.anillo': 'Ring',
  },

  // ==================== PORTUGUÉS (PT) ====================
  pt: {
    'hero.sub': 'Para Iniciantes — Sem Ofensa',
    'frase1': 'Não sou dono da Verdade — mas <span>Conhecimento + Organização = Poder.</span>',
    'frase2': 'Não tema o RNG. Ele não é seu amigo, nem seu inimigo... <span>ele só joga sugestões.</span>',
    'tracker.title': '// tracker · onde você está agora?',
    'lbl.act': 'Ato atual',
    'lbl.build': 'Tipo de build',
    'lbl.rng': 'Sua situação com o RNG',
    'lbl.sit': 'Problema atual',
    'btn.analyze': '⟶ Analisar situação',
    'sel': '— Selecionar —',
    'epilogo': 'Epílogo',
    'b.fisico': 'Físico (Guerreiro)',
    'b.veneno': 'Veneno',
    'b.elemental': 'Dano Elemental',
    'b.crit': 'Crítico',
    'b.inv': 'Invocador',
    'b.noidea': 'Ainda não sei',
    'r.bien': 'Está indo bem',
    'r.mal': 'Cai o que não preciso',
    'r.conf': 'Não sei o que fazer com o que tenho',
    'sit.none': '— Sem problema —',
    'sit.dmg': 'Baixo dano',
    'sit.glass': 'Morrendo rápido',
    'sit.stuck': 'Progresso lento',
    'sit.lucky': 'Muito loot bom',
    'philo.title': '// filosofia · o manual de adaptabilidade',
    'p1.h': 'Conhecimento é poder',
    'p1.p': 'Entender o sistema de runas, resistências e escalonamento de dano te dá <em>vantagem real</em>.',
    'p2.h': 'O RNG é neutro',
    'p2.p': 'Ele não te persegue nem te favorece. Dá opções e <em>você decide o que fazer com elas</em>.',
    'p3.h': 'O Baú é seu aliado',
    'p3.p': 'O que não serve hoje <em>é o poder de amanhã</em>. Guarde tudo.',
    'p4.h': 'Adapte-se, não force',
    'p4.p': 'Se o loot te empurra para outra direção, <em>escute</em>. Pivotar não é desistir.',
    'kl.title': '// knowledge.learned — o que ninguém te conta',
    'k1.h': 'O jogo não está vazio',
    'k1.p': '<em>"Não tenha medo se não ver muitos jogadores. O jogo pode parecer vazio no início — mas sua verdadeira natureza vive no endgame."</em>',
    'k2.h': 'Seu primeiro personagem é seu professor',
    'k2.p': 'Não é seu main — é sua escola. <em>A satisfação de chegar ao endgame é real.</em>',
    'k3.h': 'As transições são o jogo',
    'k3.p': 'Whirlwind → Toxic Flame → Icy Arrow. Cada build foi uma resposta ao que o jogo oferecia.',
    'k4.h': 'Drop ruim não existe',
    'k4.p': 'O que não usa hoje <em>é o poder de outro personagem amanhã.</em>',
    'k5.h': 'O completista é recompensado',
    'k5.p': 'Explorar cada canto e completar missões secundárias <em>não é tempo perdido</em> — o jogo recompensa.',
    'k6.h': 'Até as caixas importam',
    'k6.p': 'Quebrar barris e objetos do cenário parece insignificante — mas <em>conta para conquistas reais.</em>',
    'k7.h': 'Não precisa de alt logo',
    'k7.p': 'O jogo <em>se adapta ao progresso</em>. Aprenda primeiro o que guardar, vender e quebrar.',
    'k8.h': 'É P2W? A resposta honesta',
    'k8.p': 'Na minha experiência: <em>não</em>. Mas organização importa. Gerenciar o banco <em>vale mais que qualquer item comprado</em>.',
    'k9.h': 'Resistências caem ao progredir',
    'k9.p': 'Os 75% que tinha no Ato 3 <em>podem não segurar no Ato 7</em>. Verifique a cada episódio.',
    'k10.h': 'Alguns itens são Game Changers',
    'k10.p': 'Nem todo item é uma melhora incremental. Alguns mudam tudo — <em>um antes e depois</em>.',
    'k11.h': 'Bosses como teste de build',
    'k11.p': 'Alguns bosses são checkpoints naturais. Se não consegue passar — <em>o jogo está mostrando algo sobre sua build</em>.',
    'k12.h': 'Mudança forçada vs. Ganhos',
    'k12.p': 'Às vezes o jogo te força a perder algo — pontos do Zodíaco, stats, runas — para desbloquear progresso maior. <em>Não é punição — é o sistema se adaptando.</em>',
    'path.title': '// MEU CAMINHO: EVOLUÇÃO PÓS-64',
    'path.p1': 'Perseguia críticos amarelos entre os brancos. Visualmente satisfatório, mas resistências me pararam no Ato 6. <span style="color:var(--cyan)">Primeira lição: o jogo te avisa quando um build atinge seu limite.</span>',
    'path.p2': 'Transição para dano fixo (<span style="color:var(--red2)">Max-Min DMG</span>). Pura estabilidade para superar o pico de dificuldade. Cada mudança de build significou guardar itens diferentes — o baú começou a crescer com propósito.',
    'path.p3': 'O objetivo: <span style="color:var(--gold2);font-weight:bold;font-size:1.1rem;text-shadow:0 0 8px rgba(201,168,76,0.5)">AMARELOS MASSIVOS</span>. Velocidade e críticos imensos. Recompensa pela organização.',
    'path.zodiac.title': '// RESET DO ZODÍACO · JANELA GRATUITA',
    'path.zodiac.p': 'O jogo permite resetar o Zodíaco gratuitamente até o chefe final do Ato 10. Isso não é apenas uma vantagem — é um convite para experimentar diferentes builds sem medo. Cada tentativa gera drops diferentes, cada drop vai para o baú, e o baú cresce. <span style="color:var(--gold)">Experimentar antes do Ato 10 não é tempo perdido — é um investimento no seu inventário.</span>',
    'early.title': '📖 Early Game: cada ação conta',
    'early.intro': '"Não é um jogo difícil, mas há muito o que fazer. Cada pequena ação constrói um personagem gigante."',
    'early.comp.h': 'O Compêndio trabalha para você',
    'early.comp.p': 'Depois de desbloqueado (Act 1 ou 2), preste atenção nas runas que escolher. Evite repetí-las no início — foque em conseguir runas novas para somar pontos e obter melhorias permanentes. Cada ponto conta! O mesmo vale para itens Únicos: guarde-os para o buff passivo.',
    'early.alch.h': 'A mesa de alquimia nunca descansa',
    'early.alch.p': 'Comece o crafting cedo. Não deixe a mesa de alquimia parada — subir o nível de Maestria é a única forma de desbloquear Poções Únicas e crafting avançado mais tarde. Eficiência é a chave.',
    'early.mys.h': 'Gaste ouro em Itens Misteriosos',
    'early.mys.p': 'Entre o Mid e o Late Game, enquanto o crafting avançado ainda não é totalmente viável, gastar o ouro economizado em Itens Misteriosos é uma ótima opção. É a melhor forma de buscar bases de alto nível ou equipamentos decentes.',
    'early.ach.h': 'Tudo conta como conquista',
    'early.ach.p': 'Adicionar amigos, entrar em uma guild, completar tarefas diárias — cada ação soma pontos de progresso invisível. Os buffs diários e recompensas de guild são vitórias passivas que muitos ignoram.',
    'early.season.h': 'Temporada > Padrão (minha opinião)',
    'early.season.p': 'Se você vem de jogos como PoE, já sabe como funciona: o personagem de Temporada vai para o Padrão no final do ciclo. Mas enquanto a Temporada está ativa, tem maior drop de ouro, mais essências de alquimia e melhores chances de Únicos. Minha recomendação: comece na Temporada.',
    'early.hard.h': 'Hardcore vs Normal — não é a mesma coisa',
    'early.hard.p': 'No Hardcore, se o seu personagem morrer muitas vezes sem cuidado, as consequências serão permanentes. O Normal te dá margem para aprender sem esse peso. Para um jogador novo: comece no Normal, aprenda o jogo e, quando se sentir seguro, considere o desafio Hardcore.',
    'act.1': 'Ato 1', 'act.2': 'Ato 2', 'act.3': 'Ato 3', 'act.4': 'Ato 4', 'act.5': 'Ato 5',
    'act.6': 'Ato 6', 'act.7': 'Ato 7', 'act.8': 'Ato 8', 'act.9': 'Ato 9', 'act.10': 'Ato 10',
    'act.11': 'Ato 11', 'act.12': 'Ato 12', 'act.13': 'Ato 13',
    'og1': 'Episódio 1 — Tutorial (Atos 1–5)',
    'og2': 'Episódio 2 — O jogo começa (Atos 6–10)',
    'og3': 'Episódio 3 — Endgame (Atos 11–13)',
    'og4': 'Epílogo — Tudo desbloqueado',
    'about.title': 'Sobre',
    'about.text': 'Esta web-app reúne parte dos meus pensamentos, caminhando para uma visão mais global. Eu não estou dizendo como jogar; em vez disso, eu conto a minha história — o meu caminho pelo jogo.',
    'footer.fan': 'Feito por um fã',
    'endgame.secret': 'O endgame tem seus próprios segredos — cabe a você descobri-los.',
    'toolbar.save': '💾 Salvar build',
    'toolbar.load': '📂 Carregar',
    'toolbar.del': '🗑️ Excluir',
    'toolbar.export': '📋 Exportar',
    'toolbar.reset': '⟳ Resetar',
    'toolbar.load.ph': '— Carregar build —',
    'toolbar.del.ph': '— Excluir build —',
    'faq.title': '// faq · perguntas frequentes',
    'faq.q1': 'Por que meus buffs mudam de acordo com meus stats base?',
    'faq.a1': 'Project U não é um banco de dados estático. Usa <strong>Condicionais de Atributo Comparado</strong>. Se sua Energia supera sua Força, sua Barreira escala 10% a mais.',
    'faq.q2': 'Por que não vejo itens comuns ou raros?',
    'faq.a2': 'Project U é projetado para <strong>Theorycrafting de alto nível</strong>. Itens <em>Únicos</em> definem uma build. Itens genéricos serão adicionados em atualizações futuras.',
    'faq.q3': 'O buff do Baú se soma ao do item equipado?',
    'faq.a3': 'Sim. O sistema detecta se o item está <strong>Guardado no Baú (✦)</strong> e ativa o benefício passivo de coleção.',
    'faq.q4': 'Posso guardar mais de um exemplar do mesmo item Único?',
    'faq.a4': 'Não. Project U segue a regra do <strong>Exemplar Único</strong>. Uma vez que um item está Cinza, seu benefício fica permanente no Wardrobe.',
    'faq.q5': 'Por que o Escudo não está na aba de Armaduras?',
    'faq.a5': 'O <strong>Escudo é uma peça de mão secundária</strong>. Isso permite validar se sua build é compatível com armas de duas mãos.',
    'faq.q6': 'Como o Project U me ajuda a decidir entre dois itens únicos?',
    'faq.a6': 'O sistema de <strong>Condicionais de Atributo Comparado</strong> vai alertar se uma mudança de equipamento quebra uma sinergia de stats.',
    'faq.q7': 'Por que usamos Seal of Chaos Resist em vez de Cold Armor?',
    'faq.a7': 'Mesmo sendo uma build de Agilidade (Verde), o Selo de Resistência ao Caos (Azul) é inegociável. <strong>A armadura física não serve contra dano de Caos.</strong> Trocamos defesa física plana por sobrevivência pura.',
    'faq.q8': 'Como funciona a Metralhadora de Mobilidade?',
    'faq.a8': 'O segredo é <strong>Roll + Use Count</strong>. Com Use Count, o contador de cargas sobe para 3. Você pode se reposicionar três vezes seguidas antes do cooldown global.',
    'faq.q9': 'Qual é a importância do estado de Overheat?',
    'faq.a9': 'Icy Arrow gera Overheat, que aproveitamos com <strong>Heat Cycle</strong>. Ao atingir High Temperature (&gt;40%), recebemos <em>+126.9% de Critical Rate</em>.',
    'faq.q10': 'Por que investir tanto na Frost Sentry?',
    'faq.a10': 'A torre não é apenas dano extra — é escalonamento e controle. Com <strong>Life Imbued</strong>: +1% DMG por 2500 HP da torre. Com <strong>Precise Sentry</strong>: críticos constantes e congelamento.',
    'runes.red.label': 'Vermelho — Força',
    'runes.green.label': 'Verde — Agilidade',
    'runes.blue.label': 'Azul — Inteligência',
    'runes.white.label': 'Branco — Universal',
    'runes.red.name': 'Vermelho',
    'runes.green.name': 'Verde',
    'runes.blue.name': 'Azul',
    'runes.white.name': 'Branco',
    'runes.red.attr': 'Força (STR)',
    'runes.green.attr': 'Agilidade (AGI)',
    'runes.blue.attr': 'Inteligência (INT)',
    'runes.white.attr': 'Universal',
    'runes.red.focus': 'Sobrevivência · Físico',
    'runes.green.focus': 'Velocidade · Destreza',
    'runes.blue.focus': 'Magia · Utilidade',
    'runes.white.focus': 'Link Livre (qualquer cor)',
    'runes.table.color': 'Cor',
    'runes.table.attr': 'Atributo',
    'runes.table.focus': 'Foco de Combate',
    'runes.skill.title': '// skill runes · build atual',
    'runes.link.title': '// link runes · modificadores equipados',
    'runes.ref.text': 'Dúvidas? Veja a biblioteca completa de runas →',
    'no.conditionals': 'Sem condicionais',
    'filter.weapons': '⚔ Armas',
    'filter.armor': '🛡 Armaduras',
    'filter.acc': '💍 Acessórios',
    'filter.runes': '🔗 Link Runes',
    'stats.str': 'FOR',
    'stats.dex': 'AGI',
    'stats.int': 'INT',
    'stats.hpfull': 'HP Cheio',
    'wardrobe.active': '// bufos de armário ativos',
    'wardrobe.stored': '✦ Guardado no Baú (bufo ativo)',
    'wardrobe.store': '○ Guardar no Baú',
    'wardrobe.empty': 'Sem itens guardados.',
    'unique.badge': 'Único',
    'weapon.main.type': 'Mão Principal · Tipo',
    'weapon.main.name': 'Mão Principal · Nome',
    'weapon.off.type': 'Mão Secundária · Tipo',
    'weapon.off.name': 'Mão Secundária · Nome',
    'weapon.type.placeholder': '— Tipo de arma —',
    'weapon.name.placeholder': '— Selecione o tipo primeiro —',
    'weapon.off.none': 'Sem mão secundária',
    'btn.validate': '⟶ Validar Combinação',
    'shield.label': '🛡️ Escudo',
    'shield.none': '— Nenhum —',
    'shield.light': 'Escudo Leve',
    'shield.heavy': 'Escudo Pesado',
    'shield.tower': 'Escudo Torre',
    'shield.warning': '⚠ Não compatível com armas de duas mãos',
    'build.save.prompt': 'Nome para esta build:',
    'build.save.success': '✓ Build salva',
    'build.load.success': '✓ Build carregada',
    'build.delete.confirm': 'Excluir build?',
    'build.delete.success': '✓ Build excluída',
    'build.export.copied': '📋 Build copiada para a área de transferência!',
    'build.reset.confirm': '⚠️ Resetar TODOS os selects e stats?',
    'build.reset.success': '✓ Tudo resetado',
    'build.load.prompt': 'Selecione uma build para carregar.',
    'build.delete.prompt': 'Selecione uma build para excluir.',

    // Gear Slots
    'gear.slot.casco': 'Capacete',
    'gear.slot.pechera': 'Peitoral',
    'gear.slot.hombreras': 'Ombreiras',
    'gear.slot.guantes': 'Luvas',
    'gear.slot.botas': 'Botas',
    'gear.slot.necklace': 'Colar',
    'gear.slot.cinturon': 'Cinto',
    'gear.slot.anillo': 'Anel',
  },

  // ==================== FRANCÉS (FR) ====================
  fr: {
    'hero.sub': 'Pour les Débutants — Sans Insulte',
    'frase1': 'Je ne possède pas la Vérité — mais <span>Connaissance + Organisation = Pouvoir.</span>',
    'frase2': 'N\'aie pas peur du RNG. Ce n\'est ni ton ami, ni ton ennemi... <span>il ne fait que suggérer.</span>',
    'tracker.title': '// tracker · où en es-tu ?',
    'lbl.act': 'Acte actuel',
    'lbl.build': 'Type de build',
    'lbl.rng': 'Ta situation avec le RNG',
    'lbl.sit': 'Problème actuel',
    'btn.analyze': '⟶ Analyser ma situation',
    'sel': '— Sélectionner —',
    'epilogo': 'Épilogue',
    'b.fisico': 'Physique (Guerrier)',
    'b.veneno': 'Poison',
    'b.elemental': 'Dégâts Élémentaires',
    'b.crit': 'Critique',
    'b.inv': 'Invocateur',
    'b.noidea': 'Pas encore sûr',
    'r.bien': 'Ça se passe bien',
    'r.mal': 'Je reçois ce dont je n\'ai pas besoin',
    'r.conf': 'Je ne sais pas quoi faire de ce que j\'ai',
    'sit.none': '— Aucun problème —',
    'sit.dmg': 'Dégâts faibles',
    'sit.glass': 'Je meurs trop vite',
    'sit.stuck': 'Progression lente',
    'sit.lucky': 'Beaucoup de bons drops',
    'philo.title': '// philosophie · le manuel d\'adaptabilité',
    'p1.h': 'La connaissance, c\'est le pouvoir',
    'p1.p': 'Comprendre le système de runes, les résistances et la mise à l\'échelle des dégâts te donne un <em>vrai avantage</em>.',
    'p2.h': 'Le RNG est neutre',
    'p2.p': 'Il ne te poursuit pas et ne te favorise pas. Il te donne des options et <em>c\'est toi qui décides quoi en faire</em>.',
    'p3.h': 'Le Coffre est ton allié',
    'p3.p': 'Ce qui ne te sert pas aujourd\'hui <em>sera la puissance de demain</em>. Garde tout.',
    'p4.h': 'Adapte-toi, ne force pas',
    'p4.p': 'Si le loot te pousse dans une autre direction, <em>écoute-le</em>. Pivoter n\'est pas abandonner.',
    'kl.title': '// knowledge.learned — ce que personne ne te dit',
    'k1.h': 'Le jeu n\'est pas vide',
    'k1.p': '<em>"N\'aie pas peur si tu ne vois pas beaucoup de joueurs. Le jeu peut sembler vide au début — mais sa vraie nature vit dans l\'endgame."</em>',
    'k2.h': 'Ton premier personnage est ton prof',
    'k2.p': 'Ce n\'est pas ton main — c\'est ton école. <em>La satisfaction d\'atteindre l\'endgame est réelle.</em>',
    'k3.h': 'Les transitions, c\'est le jeu',
    'k3.p': 'Whirlwind → Toxic Flame → Icy Arrow. Chaque build était une réponse à ce que le jeu offrait.',
    'k4.h': 'Il n\'y a pas de mauvais drop',
    'k4.p': 'Ce que tu n\'utilises pas aujourd\'hui <em>sera la puissance d\'un autre personnage demain.</em>',
    'k5.h': 'Les complétionnistes sont récompensés',
    'k5.p': 'Explorer chaque recoin et faire les quêtes secondaires <em>n\'est pas du temps perdu</em> — le jeu le récompense.',
    'k6.h': 'Même les caisses comptent',
    'k6.p': 'Casser des tonneaux et des objets du décor semble insignifiant — mais <em>ça compte pour de vrais succès.</em>',
    'k7.h': 'Pas besoin d\'un alt tout de suite',
    'k7.p': 'Le jeu <em>s\'adapte seul à la progression</em>. Apprends d\'abord quoi garder, vendre et casser.',
    'k8.h': 'C\'est P2W ? La réponse honnête',
    'k8.p': 'De mon expérience : <em>non</em>. Mais l\'organisation compte. Gérer ta banque <em>vaut plus que n\'importe quel objet acheté</em>.',
    'k9.h': 'Les résistances baissent en progressant',
    'k9.p': 'Les 75% que tu avais à l\'Acte 3 <em>peuvent ne pas tenir à l\'Acte 7</em>. Vérifie-les à chaque épisode.',
    'k10.h': 'Certains items sont des Game Changers',
    'k10.p': 'Tous les items ne sont pas des améliorations progressives. Certains changent tout — <em>un avant et un après</em>.',
    'k11.h': 'Les boss comme test de build',
    'k11.p': 'Certains boss sont des checkpoints naturels. Si tu n\'y arrives pas — <em>le jeu te montre quelque chose sur ta build</em>.',
    'k12.h': 'Changement Forcé vs. Gains',
    'k12.p': 'Parfois le jeu te force à perdre quelque chose — points du Zodiaque, stats, runes — pour débloquer une progression plus grande. <em>Ce n\'est pas une punition — c\'est le système qui s\'adapte.</em>',
    'path.title': '// MON CHEMIN: ÉVOLUTION POST-64',
    'path.p1': 'À la recherche de critiques jaunes parmi les blancs. Très satisfaisant, mais les résistances m\'ont arrêté à l\'Acte 6. <span style="color:var(--cyan)">Première leçon : le jeu vous avertit quand un build a atteint son plafond.</span>',
    'path.p2': 'Transition vers les dégâts fixes (<span style="color:var(--red2)">Max-Min DMG</span>). Stabilité pure pour surmonter le pic de difficulté. Chaque changement de build signifiait sauvegarder différents objets — le coffre a commencé à grandir avec un but.',
    'path.p3': 'Le but : <span style="color:var(--gold2);font-weight:bold;font-size:1.1rem;text-shadow:0 0 8px rgba(201,168,76,0.5)">DÉGÂTS JAUNES MASSIFS</span>. Vitesse et critiques massives. Récompense pour l\'organisation.',
    'path.zodiac.title': '// RÉINITIALISATION DU ZODIAQUE · FENÊTRE GRATUITE',
    'path.zodiac.p': 'Le jeu permet de réinitialiser le Zodiaque gratuitement jusqu\'à tuer le boss final de l\'Acte 10. Ce n\'est pas qu\'un avantage — c\'est une invitation à essayer différentes builds sans peur. Chaque essai génère des butins différents, chaque butin va au coffre, et le coffre grandit. <span style="color:var(--gold)">Expérimenter avant l\'Acte 10 n\'est pas du temps perdu — c\'est un investissement dans votre inventaire.</span>',
    'early.title': '📖 Early Game: chaque action compte',
    'early.intro': '"Ce n\'est pas un jeu difficile, mais il y a beaucoup à faire. Chaque petite action construit un personnage énorme."',
    'early.comp.h': 'Le Compendium travaille pour toi',
    'early.comp.p': 'Une fois débloqué (Acte 1 ou 2), fais attention aux runes que tu choisis. <em>Évite les doublons au début</em> — concentre-toi sur de nouvelles runes pour gagner des points et des bonus permanents.',
    'early.alch.h': 'La table d\'alchimie ne se repose jamais',
    'early.alch.p': 'Commence le craft tôt. Ne laisse pas ta table inactive — monter la Maîtrise est la <em>seule façon</em> de débloquer des Potions Uniques et du craft avancé.',
    'early.mys.h': 'Dépense l\'or en Objets Mystérieux',
    'early.mys.p': 'Entre le Mid et le Late Game, dépenser ton or en <em>Objets Mystérieux</em> est un bon choix pour trouver des bases de haut niveau.',
    'early.ach.h': 'Tout compte comme succès',
    'early.ach.p': 'Ajouter des amis, rejoindre une guilde, faire des tâches quotidiennes — <em>chaque action ajoute des points de progression invisibles</em>.',
    'early.season.h': 'Saison > Standard (mon avis)',
    'early.season.p': 'Si tu viens de jeux comme PoE, tu sais déjà comment ça marche. Pendant la saison : <em>plus d\'or, plus d\'essences, meilleures chances d\'Uniques</em>. Mon conseil : commence en Saison.',
    'early.hard.h': 'Hardcore vs Normal — ce n\'est pas pareil',
    'early.hard.p': 'En Hardcore, mourir trop souvent a des conséquences permanentes. Le Normal te laisse apprendre sans cette pression. <em>Commence en Normal</em> si tu débutes.',
    'act.1': 'Acte 1', 'act.2': 'Acte 2', 'act.3': 'Acte 3', 'act.4': 'Acte 4', 'act.5': 'Acte 5',
    'act.6': 'Acte 6', 'act.7': 'Acte 7', 'act.8': 'Acte 8', 'act.9': 'Acte 9', 'act.10': 'Acte 10',
    'act.11': 'Acte 11', 'act.12': 'Acte 12', 'act.13': 'Acte 13',
    'og1': 'Épisode 1 — Tutoriel (Actes 1–5)',
    'og2': 'Épisode 2 — Le jeu commence (Actes 6–10)',
    'og3': 'Épisode 3 — Endgame (Actes 11–13)',
    'og4': 'Épilogue — Tout débloqué',
    'about.title': 'À propos',
    'about.text': 'Cette web-app contient une partie de mes réflexions, vers une vision globale. Je ne te dis pas comment jouer ; je te raconte mon histoire, mon chemin dans le jeu.',
    'footer.fan': 'Fait par un fan',
    'endgame.secret': 'L\'endgame a ses propres secrets — c\'est à toi de les découvrir.',
    'toolbar.save': '💾 Sauvegarder',
    'toolbar.load': '📂 Charger',
    'toolbar.del': '🗑️ Supprimer',
    'toolbar.export': '📋 Exporter',
    'toolbar.reset': '⟳ Réinitialiser',
    'toolbar.load.ph': '— Charger un build —',
    'toolbar.del.ph': '— Supprimer un build —',
    'faq.title': '// faq · questions fréquentes',
    'faq.q1': 'Pourquoi mes buffs changent-ils selon mes stats de base ?',
    'faq.a1': 'Project U n\'est pas une base de données statique. Il utilise des <strong>Conditions d\'Attributs Comparés</strong>. Si ton Énergie dépasse ta Force, ta Barrière scale de 10% en plus.',
    'faq.q2': 'Pourquoi je ne vois pas d\'objets communs ou rares ?',
    'faq.a2': 'Project U est conçu pour le <strong>Theorycrafting de haut niveau</strong>. Les objets <em>Uniques</em> définissent un build. Les objets génériques seront ajoutés dans de futures mises à jour.',
    'faq.q3': 'Le buff du Coffre s\'additionne-t-il à celui de l\'objet équipé ?',
    'faq.a3': 'Oui. Le système détecte si l\'objet est <strong>Stocké dans le Coffre (✦)</strong> et active le bonus passif de collection.',
    'faq.q4': 'Puis-je stocker plus d\'un exemplaire du même objet Unique ?',
    'faq.a4': 'Non. Project U suit la règle de <strong>l\'Exemplaire Unique</strong>. Une fois qu\'un objet est Gris, son bonus reste permanent dans ton Wardrobe.',
    'faq.q5': 'Pourquoi le Bouclier n\'est pas dans l\'onglet Armures ?',
    'faq.a5': 'Le <strong>Bouclier est une pièce de main secondaire</strong>. Cela permet de valider si ton build est compatible avec les armes à deux mains.',
    'faq.q6': 'Comment Project U m\'aide-t-il à choisir entre deux objets uniques ?',
    'faq.a6': 'Le système de <strong>Conditions d\'Attributs Comparés</strong> t\'avertira si un changement d\'équipement brise une synergie de stats.',
    'faq.q7': 'Pourquoi utiliser Seal of Chaos Resist plutôt que Cold Armor ?',
    'faq.a7': 'Même si c\'est un build Agilité (Vert), le Sceau de Résistance au Chaos (Bleu) est incontournable. <strong>L\'armure physique ne sert à rien contre les dégâts de Chaos.</strong>',
    'faq.q8': 'Comment fonctionne la Mitraillette de Mobilité ?',
    'faq.a8': 'Le secret est <strong>Roll + Use Count</strong>. Avec Use Count, le compteur de charges monte à 3. Tu peux te repositionner trois fois d\'affilée avant le cooldown global.',
    'faq.q9': 'Quelle est l\'importance de la Surchauffe ?',
    'faq.a9': 'Flèche Glacée génère de la Surchauffe, exploitée avec <strong>Heat Cycle</strong>. À High Temperature (&gt;40%), on reçoit <em>+126.9% de Taux de Critique</em>.',
    'faq.q10': 'Pourquoi tant investir dans Frost Sentry ?',
    'faq.a10': 'La tourelle n\'est pas que des dégâts — c\'est du scaling et du contrôle. Avec <strong>Life Imbued</strong>: +1% DMG par 2500 HP. Avec <strong>Precise Sentry</strong>: critiques constants et gel.',
    'runes.red.label': 'Rouge — Force',
    'runes.green.label': 'Vert — Agilité',
    'runes.blue.label': 'Bleu — Intelligence',
    'runes.white.label': 'Blanc — Universel',
    'runes.red.name': 'Rouge',
    'runes.green.name': 'Vert',
    'runes.blue.name': 'Bleu',
    'runes.white.name': 'Blanc',
    'runes.red.attr': 'Force (STR)',
    'runes.green.attr': 'Agilité (AGI)',
    'runes.blue.attr': 'Intelligence (INT)',
    'runes.white.attr': 'Universel',
    'runes.red.focus': 'Survie · Physique',
    'runes.green.focus': 'Vitesse · Dextérité',
    'runes.blue.focus': 'Magie · Utilité',
    'runes.white.focus': 'Lien Libre (n\'importe quelle couleur)',
    'runes.table.color': 'Couleur',
    'runes.table.attr': 'Attribut',
    'runes.table.focus': 'Focus de Combat',
    'runes.skill.title': '// runes de compétence · build actuel',
    'runes.link.title': '// runes de lien · modificateurs équipés',
    'runes.ref.text': 'Des doutes ? Consultez la bibliothèque complète →',
    'no.conditionals': 'Aucun conditionnel',
    'filter.weapons': '⚔ Armes',
    'filter.armor': '🛡 Armures',
    'filter.acc': '💍 Accessoires',
    'filter.runes': '🔗 Link Runes',
    'stats.str': 'FOR',
    'stats.dex': 'AGI',
    'stats.int': 'INT',
    'stats.hpfull': 'PV Pleins',
    'wardrobe.active': '// buffs d\'armoire actifs',
    'wardrobe.stored': '✦ Stocké dans le Coffre (buff actif)',
    'wardrobe.store': '○ Stocker dans le Coffre',
    'wardrobe.empty': 'Aucun objet stocké.',
    'unique.badge': 'Unique',
    'weapon.main.type': 'Main Principale · Type',
    'weapon.main.name': 'Main Principale · Nom',
    'weapon.off.type': 'Main Secondaire · Type',
    'weapon.off.name': 'Main Secondaire · Nom',
    'weapon.type.placeholder': '— Type d\'arme —',
    'weapon.name.placeholder': '— Sélectionnez d\'abord le type —',
    'weapon.off.none': 'Pas de main secondaire',
    'btn.validate': '⟶ Valider la Combinaison',
    'shield.label': '🛡️ Bouclier',
    'shield.none': '— Aucun —',
    'shield.light': 'Bouclier Léger',
    'shield.heavy': 'Bouclier Lourd',
    'shield.tower': 'Bouclier de Tour',
    'shield.warning': '⚠ Non compatible avec les armes à deux mains',
    'build.save.prompt': 'Nom pour ce build :',
    'build.save.success': '✓ Build sauvegardé',
    'build.load.success': '✓ Build chargé',
    'build.delete.confirm': 'Supprimer ce build ?',
    'build.delete.success': '✓ Build supprimé',
    'build.export.copied': '📋 Build copié dans le presse-papier !',
    'build.reset.confirm': '⚠️ Réinitialiser TOUS les selects et stats ?',
    'build.reset.success': '✓ Tout réinitialisé',
    'build.load.prompt': 'Sélectionnez un build à charger.',
    'build.delete.prompt': 'Sélectionnez un build à supprimer.',

    // Gear Slots
    'gear.slot.casco': 'Casque',
    'gear.slot.pechera': 'Plastron',
    'gear.slot.hombreras': 'Épaulières',
    'gear.slot.guantes': 'Gants',
    'gear.slot.botas': 'Bottes',
    'gear.slot.necklace': 'Collier',
    'gear.slot.cinturon': 'Ceinture',
    'gear.slot.anillo': 'Bague',
  },

  // ==================== COREANO (KO) ====================
  ko: {
    'hero.sub': '초보자를 위한 — 모욕 없이',
    'frase1': '나는 진실을 소유하지 않는다 — 하지만 <span>지식 + 조직 = 힘.</span>',
    'frase2': 'RNG를 두려워하지 마라. 친구도 적도 아니다... <span>그저 제안을 던질 뿐이다.</span>',
    'tracker.title': '// 트래커 · 지금 어디 있나요?',
    'lbl.act': '현재 액트',
    'lbl.build': '빌드 유형',
    'lbl.rng': 'RNG 상황',
    'lbl.sit': '현재 문제',
    'btn.analyze': '⟶ 상황 분석',
    'sel': '— 선택 —',
    'epilogo': '에필로그',
    'b.fisico': '물리 (전사)',
    'b.veneno': '독',
    'b.elemental': '속성 피해',
    'b.crit': '치명타',
    'b.inv': '소환사',
    'b.noidea': '아직 모름',
    'r.bien': '잘 되고 있다',
    'r.mal': '필요 없는 것이 드롭된다',
    'r.conf': '가진 것으로 무엇을 해야 할지 모른다',
    'sit.none': '— 문제 없음 —',
    'sit.dmg': '낮은 피해',
    'sit.glass': '너무 빨리 죽음',
    'sit.stuck': '느린 진행',
    'sit.lucky': '좋은 드롭 많음',
    'philo.title': '// 철학 · 적응 매뉴얼',
    'p1.h': '지식은 힘이다',
    'p1.p': '룬 시스템, 저항력, 피해 스케일링을 이해하면 <em>실질적인 이점</em>을 얻을 수 있다.',
    'p2.h': 'RNG는 중립이다',
    'p2.p': 'RNG는 너를 쫓거나 편애하지 않는다. 선택지를 주고 <em>네가 결정한다</em>.',
    'p3.h': '창고는 네 동맹이다',
    'p3.p': '오늘 필요 없는 것이 <em>내일의 힘</em>이 된다. 모든 것을 보관하라.',
    'p4.h': '적응하라, 강요하지 마라',
    'p4.p': '전리품이 다른 방향으로 밀면 <em>들어라</em>. 방향 전환은 포기가 아니다.',
    'kl.title': '// knowledge.learned — 아무도 말해주지 않는 것',
    'k1.h': '게임은 비어있지 않다',
    'k1.p': '<em>"주변에 플레이어가 없어도 두려워하지 마라. 게임은 처음에 비어 보일 수 있지만, 진짜 본질은 엔드게임에 있다."</em>',
    'k2.h': '첫 번째 캐릭터는 선생님이다',
    'k2.p': '메인이 아니라 학교다. <em>엔드게임에 도달하는 만족감은 진짜다.</em>',
    'k3.h': '전환이 게임이다',
    'k3.p': 'Whirlwind → Toxic Flame → Icy Arrow. 각 빌드는 게임이 제공한 것에 대한 응답이었다.',
    'k4.h': '나쁜 드롭은 없다',
    'k4.p': '오늘 사용하지 않는 것이 <em>내일 다른 캐릭터의 힘</em>이 된다.',
    'k5.h': '완성주의자는 보상받는다',
    'k5.p': '모든 구석을 탐험하고 사이드 퀘스트를 완료하는 것은 <em>낭비된 시간이 아니다</em>.',
    'k6.h': '상자도 중요하다',
    'k6.p': '통과 물체를 부수는 것은 사소해 보이지만 <em>실제 업적에 반영된다.</em>',
    'k7.h': '대체 캐릭터가 바로 필요하지 않다',
    'k7.p': '게임은 <em>스스로 진행에 적응한다</em>. 먼저 무엇을 보관하고, 팔고, 부수는지 배워라.',
    'k8.h': 'P2W인가? 솔직한 답변',
    'k8.p': '내 경험상: <em>아니다</em>. 하지만 조직이 중요하다. 은행 공간 관리가 <em>구매한 어떤 아이템보다 가치 있다</em>.',
    'k9.h': '저항력은 진행하면서 감소한다',
    'k9.p': '액트 3에서 가진 75%가 <em>액트 7에서는 충분하지 않을 수 있다</em>. 에피소드마다 확인하라.',
    'k10.h': '일부 아이템은 게임 체인저다',
    'k10.p': '모든 아이템이 점진적인 업그레이드는 아니다. 일부는 전체 방향을 바꾼다 — <em>전과 후</em>.',
    'k11.h': '보스는 빌드 테스트다',
    'k11.p': '일부 보스는 자연스러운 체크포인트 역할을 한다. 통과하지 못하면 — <em>게임이 빌드에 대해 무언가를 보여주는 것이다</em>.',
    'k12.h': '강제 변화 vs. 이득',
    'k12.p': '때로 게임은 더 큰 진행을 위해 무언가를 잃도록 강요한다. <em>벌이 아니라 시스템이 적응하는 것이다.</em>',
    'path.title': '// 내 길: 64 이후의 진화',
    'path.p1': '흰색 사이에서 노란색 크리티컬을 찾았습니다. 시각적으로 만족스럽지만, 저항 때문에 액트 6에서 멈췄습니다. <span style="color:var(--cyan)">첫 번째 교훈: 빌드가 한계에 도달하면 게임이 알려줍니다.</span>',
    'path.p2': '고정 피해로 전환(<span style="color:var(--red2)">Max-Min DMG</span>). 난이도 급등을 극복하기 위한 순수한 안정성. 빌드를 변경할 때마다 다른 아이템을 저장해야 했고, 보관함은 목적을 가지고 성장하기 시작했습니다.',
    'path.p3': '목표: <span style="color:var(--gold2);font-weight:bold;font-size:1.1rem;text-shadow:0 0 8px rgba(201,168,76,0.5)">거대한 노란색 데미지</span>. 속도와 막대한 크리티컬. 조직에 대한 보상.',
    'path.zodiac.title': '// 조디악 초기화 · 무료 기간',
    'path.zodiac.p': '게임은 액트 10 최종 보스를 처치하기 전까지 조디악을 무료로 초기화할 수 있습니다. 이것은 단순한 이점이 아닙니다 — 두려움 없이 다른 빌드를 시도하라는 초대입니다. 각 시도는 다른 드롭을 생성하고, 각 드롭은 보관함으로 이동하며, 보관함은 성장합니다. <span style="color:var(--gold)">액트 10 전에 실험하는 것은 낭비가 아닙니다 — 인벤토리에 대한 투자입니다.</span>',
    'early.title': '📖 초반 게임: 모든 행동이 중요하다',
    'early.intro': '"어려운 게임은 아니지만 할 일이 많다. 작은 행동 하나하나가 강력한 캐릭터를 만든다."',
    'early.comp.h': '컴펜디엄은 당신을 위해 작동한다',
    'early.comp.p': '해금 후 (액트 1 또는 2), 선택하는 룬에 주의를 기울여라. <em>초반에 중복을 피하라</em> — 새로운 룬 수집에 집중해 포인트와 영구 보너스를 얻어라.',
    'early.alch.h': '연금술 테이블은 쉬지 않는다',
    'early.alch.p': '일찍 제작을 시작하라. 테이블을 방치하지 마라 — 숙련도를 높이는 것이 <em>유일한 방법</em>이다.',
    'early.mys.h': '골드는 신비로운 아이템에 사용하라',
    'early.mys.p': '미드~레이트 게임에서 <em>신비로운 아이템</em>에 골드를 사용하는 것이 좋은 선택이다.',
    'early.ach.h': '모든 것이 업적으로 카운트된다',
    'early.ach.p': '친구 추가, 길드 가입, 일일 임무 완료 — <em>모든 행동이 보이지 않는 진행 포인트를 더한다</em>.',
    'early.season.h': '시즌 > 일반 (개인 의견)',
    'early.season.p': 'PoE 같은 게임을 해봤다면 이미 알 것이다. 시즌 캐릭터는 사이클 종료 시 일반으로 이동한다. 하지만 시즌 중에는 <em>더 많은 골드, 연금술 에센스, 유니크 기회</em>가 있다.',
    'early.hard.h': '하드코어 vs 일반 — 같지 않다',
    'early.hard.p': '하드코어에서 캐릭터가 너무 자주 죽으면 결과가 영구적이다. 초보자라면 <em>일반 모드에서 시작하라</em>.',
    'act.1': '액트 1', 'act.2': '액트 2', 'act.3': '액트 3', 'act.4': '액트 4', 'act.5': '액트 5',
    'act.6': '액트 6', 'act.7': '액트 7', 'act.8': '액트 8', 'act.9': '액트 9', 'act.10': '액트 10',
    'act.11': '액트 11', 'act.12': '액트 12', 'act.13': '액트 13',
    'og1': '에피소드 1 — 튜토리얼 (액트 1–5)',
    'og2': '에피소드 2 — 게임 시작 (액트 6–10)',
    'og3': '에피소드 3 — 엔드게임 (액트 11–13)',
    'og4': '에필로그 — 모두 해금됨',
    'about.title': '소개',
    'about.text': '이 웹앱에는 내 생각의 일부가 담겨 있으며, 글로벌 비전을 향해 나아간다. 플레이 방법을 알려주는 게 아니라, 내 이야기와 게임 여정을 들려주는 것이다.',
    'footer.fan': '팬이 만든 것',
    'endgame.secret': '엔드게임에는 자신만의 비밀이 있다 — 직접 발견해야 한다.',
    'toolbar.save': '💾 빌드 저장',
    'toolbar.load': '📂 불러오기',
    'toolbar.del': '🗑️ 삭제',
    'toolbar.export': '📋 내보내기',
    'toolbar.reset': '⟳ 초기화',
    'toolbar.load.ph': '— 빌드 불러오기 —',
    'toolbar.del.ph': '— 빌드 삭제 —',
    'faq.title': '// faq · 자주 묻는 질문',
    'faq.q1': '왜 내 버프가 기본 스탯에 따라 변하나요?',
    'faq.a1': 'Project U는 정적 데이터베이스가 아닙니다. <strong>비교 속성 조건부</strong>를 사용합니다. 에너지가 힘을 초과하면 방어막이 10% 더 스케일됩니다.',
    'faq.q2': '왜 일반 또는 희귀 아이템이 보이지 않나요?',
    'faq.a2': 'Project U는 고수준 <strong>이론제작</strong>을 위해 설계되었습니다. <em>유니크</em> 아이템이 빌드를 정의합니다.',
    'faq.q3': '창고 버프가 장착된 아이템 버프에 추가되나요?',
    'faq.a3': '네. 아이템이 <strong>창고에 저장(✦)</strong>되었는지 감지하고 수동 수집 혜택을 활성화합니다.',
    'faq.q4': '같은 유니크 아이템을 두 개 이상 저장할 수 있나요?',
    'faq.a4': '아니요. <strong>유니크 복사본</strong> 규칙을 따릅니다. 아이템이 회색이 되면 혜택이 영구적으로 유지됩니다.',
    'faq.q5': '왜 방패가 방어구 탭에 없나요?',
    'faq.a5': '<strong>방패는 보조 손 아이템</strong>입니다. 양손 무기와의 호환성을 올바르게 검증할 수 있습니다.',
    'faq.q6': 'Project U가 두 유니크 아이템 중 하나를 선택하는 데 어떻게 도움이 되나요?',
    'faq.a6': '<strong>비교 속성 조건부</strong> 시스템이 장비 변경이 스탯 시너지를 깨뜨리는 경우 경고합니다.',
    'faq.q7': '왜 Cold Armor 대신 Seal of Chaos Resist를 사용하나요?',
    'faq.a7': '아질리티(녹색) 빌드이지만 혼돈 저항 인장(파란색)은 필수입니다. <strong>물리 방어구는 혼돈 피해에 효과가 없습니다.</strong>',
    'faq.q8': '기동성 기관총은 어떻게 작동하나요?',
    'faq.a8': '비밀은 <strong>Roll + Use Count</strong>입니다. Use Count로 충전 횟수가 3으로 증가합니다. 글로벌 쿨다운 전에 세 번 연속으로 재배치할 수 있습니다.',
    'faq.q9': '과열 상태가 왜 중요한가요?',
    'faq.a9': '얼음 화살이 과열을 생성하고 <strong>Heat Cycle</strong>로 활용합니다. High Temperature(&gt;40%)에서 <em>+126.9% 치명타율</em>을 받습니다.',
    'faq.q10': '왜 Frost Sentry에 그렇게 많이 투자하나요?',
    'faq.a10': '포탑은 단순한 추가 피해가 아닙니다 — 스케일링과 제어입니다. <strong>Life Imbued</strong>: 포탑 2500 HP당 +1% DMG. <strong>Precise Sentry</strong>: 지속적인 치명타와 동결.',
    'runes.red.label': '빨강 — 힘',
    'runes.green.label': '초록 — 민첩',
    'runes.blue.label': '파랑 — 지능',
    'runes.white.label': '하양 — 범용',
    'runes.red.name': '빨강',
    'runes.green.name': '초록',
    'runes.blue.name': '파랑',
    'runes.white.name': '하양',
    'runes.red.attr': '힘 (STR)',
    'runes.green.attr': '민첩 (AGI)',
    'runes.blue.attr': '지능 (INT)',
    'runes.white.attr': '범용',
    'runes.red.focus': '생존 · 물리',
    'runes.green.focus': '속도 · 민첩',
    'runes.blue.focus': '마법 · 유틸리티',
    'runes.white.focus': '자유 링크 (모든 색상)',
    'runes.table.color': '색상',
    'runes.table.attr': '속성',
    'runes.table.focus': '전투 집중',
    'runes.skill.title': '// 스킬 룬 · 현재 빌드',
    'runes.link.title': '// 링크 룬 · 장착된 수정자',
    'runes.ref.text': '궁금하신 점이 있으신가요? 전체 룬 라이브러리 →',
    'no.conditionals': '조건 없음',
    'filter.weapons': '⚔ 무기',
    'filter.armor': '🛡 방어구',
    'filter.acc': '💍 액세서리',
    'filter.runes': '🔗 링크 룬',
    'stats.str': '근력',
    'stats.dex': '민첩',
    'stats.int': '지능',
    'stats.hpfull': 'HP 풀',
    'wardrobe.active': '// 활성 옷장 버프',
    'wardrobe.stored': '✦ 보관함에 저장됨 (버프 활성)',
    'wardrobe.store': '○ 보관함에 저장',
    'wardrobe.empty': '저장된 아이템이 없습니다.',
    'unique.badge': '유니크',
    'weapon.main.type': '주무기 · 유형',
    'weapon.main.name': '주무기 · 이름',
    'weapon.off.type': '보조무기 · 유형',
    'weapon.off.name': '보조무기 · 이름',
    'weapon.type.placeholder': '— 무기 유형 —',
    'weapon.name.placeholder': '— 먼저 유형을 선택하세요 —',
    'weapon.off.none': '보조무기 없음',
    'btn.validate': '⟶ 조합 확인',
    'shield.label': '🛡️ 방패',
    'shield.none': '— 없음 —',
    'shield.light': '경량 방패',
    'shield.heavy': '중량 방패',
    'shield.tower': '타워 방패',
    'shield.warning': '⚠ 양손 무기와 호환되지 않음',
    'build.save.prompt': '이 빌드의 이름:',
    'build.save.success': '✓ 빌드 저장됨',
    'build.load.success': '✓ 빌드 로드됨',
    'build.delete.confirm': '빌드를 삭제하시겠습니까?',
    'build.delete.success': '✓ 빌드 삭제됨',
    'build.export.copied': '📋 빌드가 클립보드에 복사되었습니다!',
    'build.reset.confirm': '⚠️ 모든 선택과 스탯을 초기화하시겠습니까?',
    'build.reset.success': '✓ 모두 초기화됨',
    'build.load.prompt': '로드할 빌드를 선택하세요.',
    'build.delete.prompt': '삭제할 빌드를 선택하세요.',

    // Gear Slots
    'gear.slot.casco': '투구',
    'gear.slot.pechera': '흉갑',
    'gear.slot.hombreras': '어깨보호대',
    'gear.slot.guantes': '장갑',
    'gear.slot.botas': '장화',
    'gear.slot.necklace': '목걸이',
    'gear.slot.cinturon': '허리띠',
    'gear.slot.anillo': '반지',
  },

  // ==================== CHINO (ZH) ====================
  zh: {
    'hero.sub': '为初学者 — 无冒犯',
    'frase1': '我不拥有真理 — 但 <span>知识 + 组织 = 力量。</span>',
    'frase2': '不要害怕 RNG。它不是朋友，也不是敌人... <span>它只是提出建议。</span>',
    'tracker.title': '// 追踪器 · 你现在在哪里？',
    'lbl.act': '当前章节',
    'lbl.build': '构建类型',
    'lbl.rng': '你的 RNG 情况',
    'lbl.sit': '当前问题',
    'btn.analyze': '⟶ 分析情况',
    'sel': '— 选择 —',
    'epilogo': '尾声',
    'b.fisico': '物理 (战士)',
    'b.veneno': '毒素',
    'b.elemental': '元素伤害',
    'b.crit': '暴击',
    'b.inv': '召唤师',
    'b.noidea': '还不确定',
    'r.bien': '进展顺利',
    'r.mal': '掉落的不是我需要的',
    'r.conf': '不知道怎么处理现有的东西',
    'sit.none': '— 没有问题 —',
    'sit.dmg': '伤害低',
    'sit.glass': '死得太快',
    'sit.stuck': '进度缓慢',
    'sit.lucky': '好的掉落很多',
    'philo.title': '// 哲学 · 适应手册',
    'p1.h': '知识就是力量',
    'p1.p': '理解符文系统、抗性和伤害加成，给你带来<em>真正的优势</em>。',
    'p2.h': 'RNG 是中立的',
    'p2.p': '它不追你，也不偏袒你。它给你选择，<em>你来决定怎么做</em>。',
    'p3.h': '宝箱是你的盟友',
    'p3.p': '今天用不上的东西，<em>明天就是力量</em>。什么都保留。',
    'p4.h': '适应，不要强迫',
    'p4.p': '如果战利品把你推向另一个方向，<em>听它的</em>。转变方向不是放弃。',
    'kl.title': '// knowledge.learned — 没人告诉你的事',
    'k1.h': '游戏不是空的',
    'k1.p': '<em>"不要害怕周围没有玩家。游戏一开始可能感觉空旷——但它真正的本质在终局。"</em>',
    'k2.h': '你的第一个角色是你的老师',
    'k2.p': '这不是你的主要角色——这是你的学校。<em>到达终局的满足感是真实的。</em>',
    'k3.h': '转型就是游戏',
    'k3.p': 'Whirlwind → Toxic Flame → Icy Arrow。每个构建都是对游戏所提供内容的回应。',
    'k4.h': '没有坏的掉落',
    'k4.p': '今天不用的东西，<em>明天就是另一个角色的力量。</em>',
    'k5.h': '完成主义者会得到奖励',
    'k5.p': '探索每个角落和完成支线任务<em>不是浪费时间</em>——游戏会奖励它。',
    'k6.h': '甚至箱子也很重要',
    'k6.p': '打破桶和场景物品看起来微不足道——但<em>它会计入真实成就。</em>',
    'k7.h': '不需要马上有小号',
    'k7.p': '游戏<em>自行适应进度</em>。先学会保留什么、卖什么、打碎什么。',
    'k8.h': '是 P2W 吗？诚实的回答',
    'k8.p': '根据我的经验：<em>不是</em>。但组织很重要。管理银行空间<em>比任何购买的物品都有价值</em>。',
    'k9.h': '抗性随进度下降',
    'k9.p': '第3章的75%<em>在第7章可能不够</em>。每次更换章节时检查它们。',
    'k10.h': '某些物品是游戏改变者',
    'k10.p': '并非每个物品都是渐进升级。有些会改变整个方向——<em>前后之别</em>。',
    'k11.h': 'Boss 作为构建测试',
    'k11.p': '某些Boss充当自然检查点。如果你无法通过——<em>游戏正在向你展示关于构建的某些东西</em>。',
    'k12.h': '强制变化 vs 收益',
    'k12.p': '有时游戏会强迫你失去某些东西——黄道点数、属性、符文——来解锁更大的进度。<em>这不是惩罚——是系统在适应。</em>',
    'path.title': '// 我的道路：64级后的进化',
    'path.p1': '在白色中寻找黄色暴击。视觉上令人满意，但抗性让我在第6章停了下来。<span style="color:var(--cyan)">第一课：游戏会在你的构建达到上限时提醒你。</span>',
    'path.p2': '转换为固定伤害(<span style="color:var(--red2)">Max-Min DMG</span>)。纯粹的稳定性来克服难度峰值。每次构建变更都意味着保存不同的物品 — 宝箱开始有目的地成长。',
    'path.p3': '目标：<span style="color:var(--gold2);font-weight:bold;font-size:1.1rem;text-shadow:0 0 8px rgba(201,168,76,0.5)">巨大的黄色伤害</span>。速度和大量暴击。对组织能力的回报。',
    'path.zodiac.title': '// 星盘重置 · 免费窗口',
    'path.zodiac.p': '游戏允许在第10章最终BOSS之前免费重置星盘。这不仅仅是一个优势 — 它邀请你无惧地尝试不同的构建。每次尝试都会产生不同的掉落，每次掉落都会进入宝箱，宝箱会成长。<span style="color:var(--gold)">在第10章前实验不是浪费时间 — 这是对你库存的投资。</span>',
    'early.title': '📖 早期游戏：每个行动都很重要',
    'early.intro': '"这不是一个困难的游戏，但有很多事情要做。每一个小行动都能打造出强大的角色。"',
    'early.comp.h': '图鉴为你工作',
    'early.comp.p': '解锁后（第1或2章），注意你选择的符文。<em>早期避免重复</em>——专注于收集新符文以获得积分和永久加成。',
    'early.alch.h': '炼金术台从不休息',
    'early.alch.p': '尽早开始制作。不要让炼金术台闲置——提升熟练度是<em>解锁独特药水和高级制作的唯一方法</em>。',
    'early.mys.h': '用金币购买神秘物品',
    'early.mys.p': '在中期和后期游戏之间，将积累的金币用于<em>神秘物品</em>是明智之举。',
    'early.ach.h': '一切都算作成就',
    'early.ach.p': '添加朋友、加入公会、完成每日任务——<em>每个行动都增加隐形进度点数</em>。',
    'early.season.h': '赛季 > 标准（个人看法）',
    'early.season.p': '如果你来自 PoE 等游戏，你已经知道它是如何工作的。赛季期间有<em>更高的金币掉落、更多炼金精华和更好的独特机会</em>。',
    'early.hard.h': '硬核 vs 普通 — 不一样',
    'early.hard.p': '在硬核模式中，角色死亡太多次会有永久后果。<em>初学者从普通模式开始</em>，学习游戏后再考虑硬核挑战。',
    'act.1': '第1章', 'act.2': '第2章', 'act.3': '第3章', 'act.4': '第4章', 'act.5': '第5章',
    'act.6': '第6章', 'act.7': '第7章', 'act.8': '第8章', 'act.9': '第9章', 'act.10': '第10章',
    'act.11': '第11章', 'act.12': '第12章', 'act.13': '第13章',
    'og1': '第一章节 — 教程 (章节 1–5)',
    'og2': '第二章节 — 游戏开始 (章节 6–10)',
    'og3': '第三章节 — 终局 (章节 11–13)',
    'og4': '尾声 — 全部解锁',
    'about.title': '关于',
    'about.text': '这个网络应用包含了我的一些想法，向着全球视野前进。我不是在告诉你怎么玩；而是在讲述我的故事，我在游戏中的方式。',
    'footer.fan': '由粉丝制作',
    'endgame.secret': '终局有其自己的秘密 — 等待你去发现。',
    'toolbar.save': '💾 保存构建',
    'toolbar.load': '📂 加载',
    'toolbar.del': '🗑️ 删除',
    'toolbar.export': '📋 导出',
    'toolbar.reset': '⟳ 重置',
    'toolbar.load.ph': '— 加载构建 —',
    'toolbar.del.ph': '— 删除构建 —',
    'faq.title': '// faq · 常见问题',
    'faq.q1': '为什么我的增益效果会根据基础属性变化？',
    'faq.a1': 'Project U 不是静态数据库。使用<strong>比较属性条件</strong>。如果能量超过力量，屏障额外扩展10%。',
    'faq.q2': '为什么看不到普通或稀有物品？',
    'faq.a2': 'Project U 专为<strong>高水平理论构建</strong>设计。<em>独特</em>物品定义构建。通用物品将在未来添加。',
    'faq.q3': '宝箱增益是否与装备物品的增益叠加？',
    'faq.a3': '是的。系统检测物品是否<strong>存储在宝箱中(✦)</strong>并激活被动收藏增益。',
    'faq.q4': '能存储超过一份相同独特物品吗？',
    'faq.a4': '不能。遵循<strong>唯一副本</strong>规则。一旦物品变为灰色，其收藏增益将永久保留。',
    'faq.q5': '为什么盾牌不在护甲标签中？',
    'faq.a5': '<strong>盾牌是副手装备</strong>。允许正确验证是否与双手武器兼容。',
    'faq.q6': 'Project U 如何帮助在两件独特物品之间做出选择？',
    'faq.a6': '<strong>比较属性条件</strong>系统将警告装备更换是否破坏了属性协同效应。',
    'faq.q7': '为什么使用混沌抗性印记而不是冰冷护甲？',
    'faq.a7': '尽管这是敏捷（绿色）构建，混沌抗性印记（蓝色）是必不可少的。<strong>物理护甲对混沌伤害无效。</strong>',
    'faq.q8': '机动性机关枪是如何工作的？',
    'faq.a8': '秘密是<strong>翻滚 + 使用次数</strong>。装备使用次数后，充能计数增加到3。可以在全局冷却前连续重新定位三次。',
    'faq.q9': '过热状态为什么重要？',
    'faq.a9': '寒冰箭产生过热，通过<strong>热循环</strong>利用它。在高温(&gt;40%)时获得<em>+126.9%暴击率</em>。',
    'faq.q10': '为什么在霜冻哨兵上投入那么多？',
    'faq.a10': '炮塔不仅仅是额外伤害——还有缩放和控制。<strong>生命注入</strong>: 每2500哨兵HP +1% DMG。<strong>精准哨兵</strong>: 持续暴击和冻结。',
    'runes.red.label': '红色 — 力量',
    'runes.green.label': '绿色 — 敏捷',
    'runes.blue.label': '蓝色 — 智力',
    'runes.white.label': '白色 — 通用',
    'runes.red.name': '红色',
    'runes.green.name': '绿色',
    'runes.blue.name': '蓝色',
    'runes.white.name': '白色',
    'runes.red.attr': '力量 (STR)',
    'runes.green.attr': '敏捷 (AGI)',
    'runes.blue.attr': '智力 (INT)',
    'runes.white.attr': '通用',
    'runes.red.focus': '生存 · 物理',
    'runes.green.focus': '速度 · 灵巧',
    'runes.blue.focus': '魔法 · 实用',
    'runes.white.focus': '自由链接（任意颜色）',
    'runes.table.color': '颜色',
    'runes.table.attr': '属性',
    'runes.table.focus': '战斗重点',
    'runes.skill.title': '// 技能符文 · 当前构建',
    'runes.link.title': '// 链接符文 · 已装备修改器',
    'runes.ref.text': '有疑问？查看完整符文库 →',
    'no.conditionals': '无条件',
    'filter.weapons': '⚔ 武器',
    'filter.armor': '🛡 护甲',
    'filter.acc': '💍 饰品',
    'filter.runes': '🔗 链接符文',
    'stats.str': '力量',
    'stats.dex': '敏捷',
    'stats.int': '智力',
    'stats.hpfull': '满生命',
    'wardrobe.active': '// 激活的衣橱增益',
    'wardrobe.stored': '✦ 存储在宝箱中 (增益激活)',
    'wardrobe.store': '○ 存储到宝箱',
    'wardrobe.empty': '没有存储的物品。',
    'unique.badge': '独特',
    'weapon.main.type': '主手 · 类型',
    'weapon.main.name': '主手 · 名称',
    'weapon.off.type': '副手 · 类型',
    'weapon.off.name': '副手 · 名称',
    'weapon.type.placeholder': '— 武器类型 —',
    'weapon.name.placeholder': '— 先选择类型 —',
    'weapon.off.none': '无副手',
    'btn.validate': '⟶ 验证组合',
    'shield.label': '🛡️ 盾牌',
    'shield.none': '— 无 —',
    'shield.light': '轻型盾牌',
    'shield.heavy': '重型盾牌',
    'shield.tower': '塔盾',
    'shield.warning': '⚠ 与双手武器不兼容',
    'build.save.prompt': '此构建的名称:',
    'build.save.success': '✓ 构建已保存',
    'build.load.success': '✓ 构建已加载',
    'build.delete.confirm': '删除构建？',
    'build.delete.success': '✓ 构建已删除',
    'build.export.copied': '📋 构建已复制到剪贴板！',
    'build.reset.confirm': '⚠️ 重置所有选择和属性？',
    'build.reset.success': '✓ 全部已重置',
    'build.load.prompt': '选择要加载的构建。',
    'build.delete.prompt': '选择要删除的构建。',

    // Gear Slots
    'gear.slot.casco': '头盔',
    'gear.slot.pechera': '胸甲',
    'gear.slot.hombreras': '肩甲',
    'gear.slot.guantes': '手套',
    'gear.slot.botas': '靴子',
    'gear.slot.necklace': '项链',
    'gear.slot.cinturon': '腰带',
    'gear.slot.anillo': '戒指',
  },

  // ==================== RUSO (RU) ====================
  ru: {
    'hero.sub': 'Для Начинающих — Без Обид',
    'frase1': 'Я не владею Истиной — но <span>Знание + Организация = Сила.</span>',
    'frase2': 'Не бойся RNG. Он не друг и не враг... <span>он просто подбрасывает подсказки.</span>',
    'tracker.title': '// трекер · где ты сейчас?',
    'lbl.act': 'Текущий акт',
    'lbl.build': 'Тип билда',
    'lbl.rng': 'Твоя ситуация с RNG',
    'lbl.sit': 'Текущая проблема',
    'btn.analyze': '⟶ Анализировать ситуацию',
    'sel': '— Выбрать —',
    'epilogo': 'Эпилог',
    'b.fisico': 'Физический (Воин)',
    'b.veneno': 'Яд',
    'b.elemental': 'Элементальный урон',
    'b.crit': 'Критический',
    'b.inv': 'Призыватель',
    'b.noidea': 'Пока не знаю',
    'r.bien': 'Всё идёт хорошо',
    'r.mal': 'Падает то, что не нужно',
    'r.conf': 'Не знаю, что делать с тем, что есть',
    'sit.none': '— Без проблем —',
    'sit.dmg': 'Низкий урон',
    'sit.glass': 'Умираю слишком быстро',
    'sit.stuck': 'Медленный прогресс',
    'sit.lucky': 'Отличный лут',
    'philo.title': '// философия · руководство по адаптации',
    'p1.h': 'Знание — сила',
    'p1.p': 'Понимание системы рун, сопротивлений и масштабирования урона даёт тебе <em>реальное преимущество</em>.',
    'p2.h': 'RNG нейтрален',
    'p2.p': 'Он не преследует и не favoritизирует. Даёт варианты — <em>ты решаешь, что с ними делать</em>.',
    'p3.h': 'Сундук — твой союзник',
    'p3.p': 'То, что сегодня не нужно, <em>завтра станет силой</em>. Храни всё.',
    'p4.h': 'Адаптируйся, не форсируй',
    'p4.p': 'Если лут толкает в другую сторону, <em>прислушайся</em>. Смена курса — это не поражение.',
    'kl.title': '// knowledge.learned — то, чего никто не говорит',
    'k1.h': 'Игра не пустая',
    'k1.p': '<em>"Не бойся, если не видишь других игроков. Игра кажется пустой поначалу — но её настоящая природа живёт в эндгейме."</em>',
    'k2.h': 'Первый персонаж — твой учитель',
    'k2.p': 'Это не твой мейн — это твоя школа. <em>Удовлетворение от достижения эндгейма реально.</em>',
    'k3.h': 'Переходы — это и есть игра',
    'k3.p': 'Вихрь → Токсичное Пламя → Ледяная Стрела. Каждый билд был ответом на то, что предлагала игра.',
    'k4.h': 'Плохого дропа не бывает',
    'k4.p': 'То, что не нужно сегодня, <em>завтра станет силой другого персонажа.</em>',
    'k5.h': 'Коллекционеры вознаграждаются',
    'k5.p': 'Исследование каждого уголка и выполнение заданий <em>не потраченное время</em> — игра это вознаграждает.',
    'k6.h': 'Даже ящики важны',
    'k6.p': 'Ломать бочки и объекты на сцене кажется незначительным — но <em>это засчитывается в достижения.</em>',
    'k7.h': 'Альт не нужен сразу',
    'k7.p': 'Игра <em>сама адаптируется к прогрессу</em>. Сначала научись что хранить, что продавать и что ломать.',
    'k8.h': 'P2W? Честный ответ',
    'k8.p': 'По моему опыту: <em>нет</em>. Но организация важна. Управление банком <em>стоит больше любого купленного предмета</em>.',
    'k9.h': 'Сопротивления падают при прогрессе',
    'k9.p': '75% в Акте 3 <em>может не хватить в Акте 7</em>. Проверяй их при каждой смене эпизода.',
    'k10.h': 'Некоторые предметы меняют всё',
    'k10.p': 'Не каждый предмет — просто апгрейд. Некоторые меняют весь курс — <em>до и после</em>.',
    'k11.h': 'Боссы как тест билда',
    'k11.p': 'Некоторые боссы — естественные чекпоинты. Если не можешь пройти — <em>игра показывает что-то о твоём билде</em>.',
    'k12.h': 'Принудительное изменение vs. Выгода',
    'k12.p': 'Иногда игра заставляет потерять что-то — очки Зодиака, статы, руны — чтобы открыть больший прогресс. <em>Это не наказание — это адаптация системы.</em>',
    'path.title': '// МОЙ ПУТЬ: ЭВОЛЮЦИЯ ПОСЛЕ-64',
    'path.p1': 'Охотился на жёлтые криты среди белых. Визуально удовлетворительно, но сопротивления остановили меня в Акте 6. <span style="color:var(--cyan)">Первый урок: игра подсказывает, когда билд достиг своего потолка.</span>',
    'path.p2': 'Переход на фиксированный урон (<span style="color:var(--red2)">Max-Min DMG</span>). Чистая стабильность для преодоления пика сложности. Каждое изменение билда означало сохранение разных предметов — сундук начал расти с целью.',
    'path.p3': 'Цель: <span style="color:var(--gold2);font-weight:bold;font-size:1.1rem;text-shadow:0 0 8px rgba(201,168,76,0.5)">ОГРОМНЫЕ ЖЁЛТЫЕ</span>. Скорость и массивные криты. Награда за организацию.',
    'path.zodiac.title': '// СБРОС ЗОДИАКА · БЕСПЛАТНОЕ ОКНО',
    'path.zodiac.p': 'Игра позволяет сбросить Зодиак бесплатно до убийства финального босса Акта 10. Это не просто преимущество — это приглашение пробовать разные билды без страха. Каждая попытка генерирует разные дропы, каждый дроп идёт в сундук, и сундук растёт. <span style="color:var(--gold)">Экспериментировать перед Актом 10 — это инвестиция в инвентарь.</span>',
    'early.title': '📖 Ранняя игра: каждый шаг важен',
    'early.intro': '"Это не сложная игра, но в ней очень много механик. Каждое маленькое действие создаёт мощного персонажа."',
    'early.comp.h': 'Компендиум работает на вас',
    'early.comp.p': 'Как только откроете его (Акт 1 или 2), следите за тем, какие руны выбираете. Избегайте повторов в начале — сосредоточьтесь на получении новых рун, чтобы набирать очки и получать постоянные бонусы. Каждое очко на счету! То же самое касается уникальных предметов: сохраняйте их для пассивных баффов.',
    'early.alch.h': 'Алхимический стол никогда не простаивает',
    'early.alch.p': 'Начинайте крафт как можно раньше. Не оставляйте стол без дела — повышение уровня Мастерства (Mastery) — это единственный способ разблокировать уникальные зелья и продвинутый крафт в будущем. Эффективность — залог успеха.',
    'early.mys.h': 'Тратьте золото на Таинственные предметы',
    'early.mys.p': 'В промежутке между мид-геймом и лейт-геймом, когда продвинутый крафт еще не совсем доступен, тратить накопленное золото на Таинственные предметы — отличный вариант. Это лучший способ получить высокоуровневые базы или достойное снаряжение.',
    'early.ach.h': 'Все считается достижением',
    'early.ach.p': 'Добавление друзей, вступление в гильдию, выполнение ежедневных заданий — каждое действие добавляет очки невидимого прогресса. Ежедневные баффы и награды гильдии — это пассивные бонусы, которые многие игнорируют.',
    'early.season.h': 'Сезон > Стандарт (личное мнение)',
    'early.season.p': 'Если вы пришли из таких игр, как PoE, вы уже знаете, как это работает: сезонный персонаж переходит в стандартный режим в конце цикла. Но пока идет сезон, в нем выше шанс выпадения золота, больше алхимических эссенций и лучше шансы на уникальные предметы. Моя рекомендация: начинайте в Сезоне.',
    'early.hard.h': 'Хардкор vs Обычный режим — это не одно и то же',
    'early.hard.p': 'В Хардкоре, если ваш персонаж умирает слишком часто из-за неосторожности, последствия будут постоянными. Обычный режим дает возможность учиться без этого давления. Для новичка: начните в обычном режиме, изучите игру, и когда почувствуете уверенность, переходите к испытаниям Хардкора.',
    'act.1': 'Акт 1', 'act.2': 'Акт 2', 'act.3': 'Акт 3', 'act.4': 'Акт 4', 'act.5': 'Акт 5',
    'act.6': 'Акт 6', 'act.7': 'Акт 7', 'act.8': 'Акт 8', 'act.9': 'Акт 9', 'act.10': 'Акт 10',
    'act.11': 'Акт 11', 'act.12': 'Акт 12', 'act.13': 'Акт 13',
    'og1': 'Эпизод 1 — Обучение (Акты 1–5)',
    'og2': 'Эпизод 2 — Игра начинается (Акты 6–10)',
    'og3': 'Эпизод 3 — Эндгейм (Акты 11–13)',
    'og4': 'Эпилог — Всё разблокировано',
    'about.title': 'О проекте',
    'about.text': 'В этом веб-приложении — часть моих мыслей и путь к глобальному видению. Я не учу вас играть; я рассказываю свою историю или свой путь в этой игре.',
    'footer.fan': 'Сделано фанатом',
    'endgame.secret': 'У эндгейма есть свои секреты — их вам предстоит открыть самим.',
    'toolbar.save': '💾 Сохранить билд',
    'toolbar.load': '📂 Загрузить',
    'toolbar.del': '🗑️ Удалить',
    'toolbar.export': '📋 Экспорт',
    'toolbar.reset': '⟳ Сбросить',
    'toolbar.load.ph': '— Загрузить билд —',
    'toolbar.del.ph': '— Удалить билд —',
    'faq.title': '// faq · часто задаваемые вопросы',
    'faq.q1': 'Почему мои баффы меняются в зависимости от базовых статов?',
    'faq.a1': 'Project U — не статическая база данных. Используются <strong>Условные Сравнения Атрибутов</strong>. Если Энергия превышает Силу, Барьер масштабируется на 10% больше.',
    'faq.q2': 'Почему я не вижу обычные или редкие предметы?',
    'faq.a2': 'Project U разработан для <strong>теоркрафтинга высокого уровня</strong>. <em>Уникальные</em> предметы определяют билд. Обычные предметы будут добавлены в будущих обновлениях.',
    'faq.q3': 'Суммируется ли бафф Сундука с баффом экипированного предмета?',
    'faq.a3': 'Да. Система определяет, хранится ли предмет <strong>в Сундуке (✦)</strong>, и активирует пассивный бонус коллекции.',
    'faq.q4': 'Можно ли хранить более одного экземпляра уникального предмета?',
    'faq.a4': 'Нет. Project U следует правилу <strong>Уникального Экземпляра</strong>. Как только предмет становится серым, его бонус остаётся навсегда.',
    'faq.q5': 'Почему Щит не находится во вкладке Брони?',
    'faq.a5': '<strong>Щит — это предмет второй руки</strong>. Это позволяет корректно проверить совместимость с двуручным оружием.',
    'faq.q6': 'Как Project U помогает выбрать между двумя уникальными предметами?',
    'faq.a6': 'Система <strong>Условных Сравнений Атрибутов</strong> предупредит, если смена снаряжения нарушает синергию статов.',
    'faq.q7': 'Почему мы используем Seal of Chaos Resist вместо Cold Armor?',
    'faq.a7': 'Хотя это билд Ловкости (Зелёный), Печать сопротивления Хаосу (Синяя) обязательна. <strong>Физическая броня бесполезна против урона Хаоса.</strong> Мы жертвуем физической защитой ради выживаемости.',
    'faq.q8': 'Как работает Пулемёт Мобильности?',
    'faq.a8': 'Секрет в <strong>Roll + Use Count</strong>. Use Count поднимает счётчик зарядов до 3. Можно переместиться три раза подряд до глобального кулдауна.',
    'faq.q9': 'Почему важно состояние Перегрева?',
    'faq.a9': 'Ледяная стрела генерирует Перегрев, который мы используем с <strong>Heat Cycle</strong>. При High Temperature (&gt;40%) получаем <em>+126.9% крит. рейта</em>.',
    'faq.q10': 'Зачем столько вкладывать в Frost Sentry?',
    'faq.a10': 'Турель — это не просто урон, это масштабирование и контроль. С <strong>Life Imbued</strong>: +1% урона на каждые 2500 HP турели. С <strong>Precise Sentry</strong>: постоянные криты и заморозка.',
    'runes.red.label': 'Красный — Сила',
    'runes.green.label': 'Зелёный — Ловкость',
    'runes.blue.label': 'Синий — Интеллект',
    'runes.white.label': 'Белый — Универсальный',
    'runes.red.name': 'Красный',
    'runes.green.name': 'Зелёный',
    'runes.blue.name': 'Синий',
    'runes.white.name': 'Белый',
    'runes.red.attr': 'Сила (STR)',
    'runes.green.attr': 'Ловкость (AGI)',
    'runes.blue.attr': 'Интеллект (INT)',
    'runes.white.attr': 'Универсальный',
    'runes.red.focus': 'Выживание · Физический',
    'runes.green.focus': 'Скорость · Ловкость',
    'runes.blue.focus': 'Магия · Утилита',
    'runes.white.focus': 'Свободный Слот (любой цвет)',
    'runes.table.color': 'Цвет',
    'runes.table.attr': 'Атрибут',
    'runes.table.focus': 'Боевой Фокус',
    'runes.skill.title': '// руны навыков · текущий билд',
    'runes.link.title': '// руны связи · экипированные модификаторы',
    'runes.ref.text': 'Сомнения? Полная библиотека рун →',
    'no.conditionals': 'Без условий',
    'filter.weapons': '⚔ Оружие',
    'filter.armor': '🛡 Броня',
    'filter.acc': '💍 Аксессуары',
    'filter.runes': '🔗 Линк Руны',
    'stats.str': 'СИЛ',
    'stats.dex': 'ЛОВ',
    'stats.int': 'ИНТ',
    'stats.hpfull': 'HP полное',
    'wardrobe.active': '// активные баффы гардероба',
    'wardrobe.stored': '✦ Хранится в Сундуке (бафф активен)',
    'wardrobe.store': '○ Хранить в Сундуке',
    'wardrobe.empty': 'Нет сохранённых предметов.',
    'unique.badge': 'Уникальный',
    'weapon.main.type': 'Основная рука · Тип',
    'weapon.main.name': 'Основная рука · Название',
    'weapon.off.type': 'Вспомогательная рука · Тип',
    'weapon.off.name': 'Вспомогательная рука · Название',
    'weapon.type.placeholder': '— Тип оружия —',
    'weapon.name.placeholder': '— Сначала выберите тип —',
    'weapon.off.none': 'Нет оружия во второй руке',
    'btn.validate': '⟶ Проверить Комбинацию',
    'shield.label': '🛡️ Щит',
    'shield.none': '— Нет —',
    'shield.light': 'Лёгкий Щит',
    'shield.heavy': 'Тяжёлый Щит',
    'shield.tower': 'Башенный Щит',
    'shield.warning': '⚠ Несовместимо с двуручным оружием',
    'build.save.prompt': 'Название для этого билда:',
    'build.save.success': '✓ Билд сохранён',
    'build.load.success': '✓ Билд загружен',
    'build.delete.confirm': 'Удалить билд?',
    'build.delete.success': '✓ Билд удалён',
    'build.export.copied': '📋 Билд скопирован в буфер обмена!',
    'build.reset.confirm': '⚠️ Сбросить ВСЕ выборы и статы?',
    'build.reset.success': '✓ Всё сброшено',
    'build.load.prompt': 'Выберите билд для загрузки.',
    'build.delete.prompt': 'Выберите билд для удаления.',

    // Gear Slots
    'gear.slot.casco': 'Шлем',
    'gear.slot.pechera': 'Нагрудник',
    'gear.slot.hombreras': 'Наплечники',
    'gear.slot.guantes': 'Перчатки',
    'gear.slot.botas': 'Сапоги',
    'gear.slot.necklace': 'Ожерелье',
    'gear.slot.cinturon': 'Пояс',
    'gear.slot.anillo': 'Кольцо',
  },
};

// Reordenación jerárquica global según prioridad: EN → FR → KO → ZH → RU → PT → ES
const T = {
  en: T_raw.en,
  fr: T_raw.fr,
  ko: T_raw.ko,
  zh: T_raw.zh,
  ru: T_raw.ru,
  pt: T_raw.pt,
  es: T_raw.es,
};